### ISSUE TITLE
[Question] Is the text `SDK + pllugx` on the vfox logo expected?

### ISSUE THREAD

**Issue by vikiboss** [version-fox/vfox#102]
**Version**

null

**OS**

null

**Question Description**

Is the text `SDK + pllugx` on the vfox logo expected? imo, you may wanna use `SDK + plugin(x)` or `SDK + plug(x)`?

> btw, the letter `u` and `g` on the logo are too close.

**Comment by aooohan** [comment]
I'm a bit embarrassed to say that I had this logo generated by GPT, and I noticed `pllugx`, but since it looks nice, and since I can't draw this kind of logo 😅, I had to accept it, no harm no foul.

**Comment by vikiboss** [comment]
🤣🤣 Lol, get it. 

I think the gear and SDK on the logo are clear enough. If you can't modify the text, is it possible to remove the text on the logo to keep it clear?

Nothing much, just a suggestion, and feel free to give it a try.
