### ISSUE TITLE
[Feature]: Cmake plugin

### ISSUE THREAD

**Issue by pwall2222** [version-fox/vfox#104]
https://cmake.org/

**Comment by ahai-code** [comment]
@pwall2222 The Cmake plugin is provided and you can use it by executing the` vfox add cmake` command in vfox (version >= 3.0).

**Comment by lmj01** [comment]
@ahai-code The CMake plugin can support WSL ?
I got the error, can show the version of cmake, but when i press the enter, got this message:
plugin [PreInstall] method error: no version number provided.

I can install CMake on window and linux, but on WSL got some problem.
I need some env to development some lib
