### ISSUE TITLE
[Feature]: Amazon Corretto JDK Plugin

### ISSUE THREAD

**Issue by AoEiuV020** [version-fox/vfox#106]
https://aws.amazon.com/cn/corretto/?filtered-posts.sort-by=item.additionalFields.createdDate&filtered-posts.sort-order=desc

老实说我并不清楚各种openjdk的差异，
但也正是因此看vfox支持的一堆java中没有我一直用的android studio / idea下载的corretto导致有点选择困难症了，希望添加支持，

![image](https://github.com/version-fox/vfox/assets/11682198/44d31db6-602c-4015-836b-fa6786b6e029)

**Comment by aooohan** [comment]
感兴趣可以提个pr, 也不是很麻烦. ;)
