### ISSUE TITLE
[BUG]: Compatible with M1 mac below Node.js 16.0.0

### ISSUE THREAD

**Issue by kuroimachi** [version-fox/vfox#113]
VersionFox version 0.2.4
![1710416351958](https://github.com/version-fox/vfox/assets/46278027/c7f93da9-cb81-401b-b09f-0a09f15e5f1b)

**Comment by kuroimachi** [comment]
就项目需要用到v12 v14版本

**Comment by eryajf** [comment]
+1，把nvm卸载了，结果发现vfox安装不了🤣

**Comment by aooohan** [comment]
![image](https://github.com/version-fox/vfox/assets/40265686/45f330e4-6c6b-40e6-9f25-84629fde6104)


没什么问题， 检查一下你们的网行不行。 或者换nodejs/npmmirror

**Comment by kuroimachi** [comment]
<img width="970" alt="image" src="https://github.com/version-fox/vfox/assets/46278027/64abf1fb-15a2-4f18-9237-5a59e14b9e93">
<img width="389" alt="image" src="https://github.com/version-fox/vfox/assets/46278027/15d586fa-6097-4c41-a59e-da7cda5da250">

都没用，其他java maven都可以下载，只有nodejs的两个插件nodejs或者npmmirror不管走不走代理都下载不了，16版本以上可以下载。有手动下载版本通过命令安装的方式吗？

**Comment by kuroimachi** [comment]
发现了 windows可以 但是macos不行

**Comment by aooohan** [comment]
<img width="948" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/341481d5-862d-4dd1-b883-b9b7183c961c">

@kuroimachi 我macos 也可以啊..... 你卸载插件重新装...

**Comment by aooohan** [comment]
@kuroimachi 你是什么架构, 会不会是node低版本没有你这个架构的二进制包啊

**Comment by kuroimachi** [comment]
<img width="280" alt="image" src="https://github.com/version-fox/vfox/assets/46278027/0b9eb655-1824-4ddb-8df0-86b78bab22bd">
<img width="379" alt="image" src="https://github.com/version-fox/vfox/assets/46278027/b57cc111-8c0d-40d6-a6a4-c143a33c7d75">
我是从nvm sdkman切换过来的，nvm16 14 12都能安装使用

**Comment by aooohan** [comment]
<img width="719" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/eb34880e-657f-4012-afb3-98b735ea5fe7">

@kuroimachi  我刚看了一下, 确实没有arm, nvm能安装? 用了什么魔法吗哈哈哈哈, 能截图一下nvm 安装arm 12.9.0的图吗

**Comment by aooohan** [comment]
详见: https://github.com/nvm-sh/nvm/issues/2350

摘自: https://github.com/nvm-sh/nvm/blob/81fc05684de8b0b13aed401de64733e1d5d23a9a/README.md#troubleshooting-on-macos

> Note For Macs with the M1 chip, node started providing arm64 arch darwin packages since v16.0.0. For earlier versions, there were only darwin_x64 packages available but no darwin_arm64. If you are facing issues installing node using nvm, you may want to update to v16 or later.

看了一下, 和vfox问题一样, 只不过nvm做了些处理.  直接下载的x86. 笑死了

https://github.com/nvm-sh/nvm/blob/81fc05684de8b0b13aed401de64733e1d5d23a9a/nvm.sh#L2098-L2101
```shell
  if nvm_version_greater '16.0.0' "${VERSION}"; then
    if [ "_${NVM_OS}" = '_darwin' ] && [ "${NVM_ARCH}" = 'arm64' ]; then
      NVM_ARCH=x64
    fi
```

**Comment by aooohan** [comment]
@kuroimachi 可以先临时这么处理, https://github.com/nvm-sh/nvm/issues/2350#issuecomment-969947270, 下个Node插件版本修复

**Comment by kuroimachi** [comment]
哈哈 感谢感谢

**Comment by aooohan** [comment]
@kuroimachi 感兴趣的话可以提个PR, 我看了一下, 两行代码就能搞定.... 😄

**Comment by kuroimachi** [comment]
[fix Compatible with M1 mac below Node.js 16.0.0 #30](https://github.com/version-fox/version-fox-plugins/pull/30)
提交了

**Comment by aooohan** [comment]
@kuroimachi 感谢贡献, 直接vfox update nodejs就可以用了

**Comment by bytemain** [comment]
nvm 还有一个很厉害的功能， nvm install -s 14，可以在 arm 机器上下载 node 源码然后编译安装。

**Comment by kuroimachi** [comment]
> nvm 还有一个很厉害的功能， nvm install -s 14，可以在 arm 机器上下载 node 源码然后编译安装。

上面源码说了 低版本直接按照windows版本下载的🤣

**Comment by bytemain** [comment]
> > nvm 还有一个很厉害的功能， nvm install -s 14，可以在 arm 机器上下载 node 源码然后编译安装。
> 
> 上面源码说了 低版本直接按照windows版本下载的🤣

加上 -s 这个参数
