### ISSUE TITLE
[Question] How switch different jdk distributions

### ISSUE THREAD

**Issue by fangzhengjin** [version-fox/vfox#114]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
0.2.4

**OS**
macOS

**Question Description**
I need to install both adoptium-jdk and azul-jdk, because only azul-jdk has jdk8 that can run on macOS arm64.

**Comment by aooohan** [comment]
You can use aliases to differentiate.

```shell
vfox add --alias adoptium-jdk java/adoptium-jdk
vfox add --alias azul-jdk java/azul-jdk

vfox use azul-jdk@8
```

**Comment by fangzhengjin** [comment]
<img width="229" alt="image" src="https://github.com/version-fox/vfox/assets/12680972/d3011240-040c-48e7-be4e-0b93bf20403f">

@aooohan How to unuse java-azul or java-tem ?

**Comment by fangzhengjin** [comment]
<img width="1171" alt="image" src="https://github.com/version-fox/vfox/assets/12680972/b698a332-94ab-447d-9e35-9a605a03077a">

Whether you can use a different release as a version suffix, such as sdkman, for example: `8-tem`、`21-tem`、`21-azul`.

<img width="1017" alt="image" src="https://github.com/version-fox/vfox/assets/12680972/3212e863-461a-4e47-8976-b5abd313b689">

Cache dir ⬇️

<img width="1007" alt="image" src="https://github.com/version-fox/vfox/assets/12680972/8068b608-8528-4fe0-a405-e3573a0f0781">

**Comment by aooohan** [comment]
> @aooohan How to unuse java-azul or java-tem ?

There is currently no way to unuse. 

> Whether you can use a different release as a version suffix, such as sdkman, for example: 8-tem、21-tem、21-azul.

Good suggestion, we are preparing to refactor the plug-in mechanism, we can consider this.

**Comment by fangzhengjin** [comment]
> > @aooohan How to unuse java-azul or java-tem ?
> 
> There is currently no way to unuse.
> 
> > Whether you can use a different release as a version suffix, such as sdkman, for example: 8-tem、21-tem、21-azul.
> 
> Good suggestion, we are preparing to refactor the plug-in mechanism, we can consider this.

I found that sdkman uses API from different distributions of OpenJDK: https://github.com/foojayio/discoapi

Maybe we can adjust the operation step of installing JDK:
1. List all different distributions: https://api.foojay.io/disco/v3.0/distributions?include_versions=false&include_synonyms=false
2. User select different distributions.
3. List all different distributions version: https://api.foojay.io/disco/v3.0/packages?distribution=temurin&architecture=aarch64&archive_type=tar.gz&package_type=jdk&operating_system=macos&release_status=ga&directly_downloadable=true&free_to_use_in_production=true&tck_tested=true
4. User select jdk version.
5. Download and install jdk(from step 3 responsed `pkg_info_uri`).

Use JDK:
1. List the installed jdk(sort by version, group by distro_name)
- {distro_name}-jdk version
- Temurin-21.0.2+13

**Comment by aooohan** [comment]
@fangzhengjin Good work! It's feasible, and we can wait until the plugin system is refactored to do this.

**Comment by fangzhengjin** [comment]
Okay, I'm just mentioning that the current plug-in system does not seem to support users to choose many times. The new plug-in system may need to consider this matter.





------------------ Original ------------------
From: Han Li ***@***.***&gt;
Date: Mon,Mar 18,2024 10:06 AM
To: version-fox/vfox ***@***.***&gt;
Cc: ZhengJin ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [version-fox/vfox] [Question] How switch different jdkdistributions (Issue #114)





 
@fangzhengjin Good work! It's feasible, and we can wait until the plugin system is refactored to do this.
