### ISSUE TITLE
[Feature]: Support for switching registry address

### ISSUE THREAD

**Issue by ncnnnnn** [version-fox/vfox#119]
#### 1. Your usage scenarios?
add 插件现在是 "github.com/urfave/cli/v2" 等

#### 2. What is your expected outcome?
希望能支持自己add 本地 lua
或者 指定第三方路径
或者 支持代理

**Comment by ncnnnnn** [comment]
只是一个用法，例如

  vfox available 会
: Get "https://version-fox.github.io/version-fox-plugins/"  net/http: TLS handshake timeout

能否也指定本地

**Comment by aooohan** [comment]
available是用来查看远端仓库可用插件的, 没办法本地. 

目前可以通过配置代理解决. 
https://vfox.lhan.me/zh-hans/guides/configuration.html#%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE

**Comment by aooohan** [comment]
related #125
