### ISSUE TITLE
plugin [PostInstall] method error: <string>:122: error installing python

### ISSUE THREAD

**Issue by sd4sd54s** [version-fox/vfox#122]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
The version you are currently using
0.2.6
**OS**
Windows 10

**Question Description**
A clear and concise description of what the question is.
![1710830214901](https://github.com/version-fox/vfox/assets/92567084/394ae5dc-53e5-4e0e-9bd8-c8702589880c)

**Comment by CoderConan** [comment]
same

**Comment by x-Ai** [comment]
看了lua脚本，`local filename = sdkInfo.note` 拿不到文件名，`qInstallFile` 使用 `local path = sdkInfo.path`这是python安装后的路径。0.2.4的时候没有这个问题python可以正常安装，不知道0.2.6改了啥。等作者修复吧。🙏

**Comment by aooohan** [comment]
> 看了lua脚本，`local filename = sdkInfo.note` 拿不到文件名，`qInstallFile` 使用 `local path = sdkInfo.path`这是python安装后的路径。0.2.4的时候没有这个问题python可以正常安装，不知道0.2.6改了啥。等作者修复吧。🙏

好眼力! 确实是PreInstall之前改版导致的问题. 没有透传note.
