### ISSUE TITLE
[BUG]: vfox use -g xxxx does not work on mac os

### ISSUE THREAD

**Issue by juemeng** [version-fox/vfox#127]
**Version**
0.2.6
**OS**
macOS

**Describe the bug**
vfox use -g xxxx does not work. only works on current session. not in global

**Comment by aooohan** [comment]
I have not reproduced the issue, please provide a screenshot. Also make sure that you have configured it correctly according to [the documentation](https://vfox.lhan.me/guides/quick-start.html#_2-hook-vfox-to-your-shell)

**Comment by juemeng** [comment]
![2oksl-ip4ys](https://github.com/version-fox/vfox/assets/1787317/2df250ab-1281-4120-9de1-703ac863caaa)
I'm very sure I did the configuration correctly. please see gif above.
