### ISSUE TITLE
文档中在powershell中挂载vfox的介绍部分会提示该文件找不到

### ISSUE THREAD

**Issue by leihenshang** [version-fox/vfox#130]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
v2.6.0

**OS**
Windows 11 home basic

**Question Description**
![image](https://github.com/version-fox/vfox/assets/26454042/d2b83e70-d309-40b5-b431-37fc72c27a22)

这里会一般性提示：找不到该文件，导致下面的编辑Powershell文件失败。
建议加上以下说明：
echo $profile # 打印配置文件路径
Test-Path $profile  # 测试ps配置文件是否存在，如果为false，则先用下面的命令建立配置文件
New-Item -Path $profile -Type File –Force

**Comment by aooohan** [comment]
@leihenshang 有兴趣提个PR修改一下吗? ;)

**Comment by leihenshang** [comment]
> @leihenshang 有兴趣提个PR修改一下吗? ;)

当然，但是我不知道你们文档的仓库在哪。我们来想提个PR的来着。😅

**Comment by aooohan** [comment]
> > @leihenshang 有兴趣提个PR修改一下吗? ;)
> 
> 当然，但是我不知道你们文档的仓库在哪。我们来想提个PR的来着。😅

哈哈哈哈哈, docs目录下. 下面两处位置.

https://github.com/version-fox/vfox/blob/main/docs/guides/quick-start.md

https://github.com/version-fox/vfox/blob/main/docs/zh-hans/guides/quick-start.md

**Comment by leihenshang** [comment]
> > > @leihenshang 有兴趣提个PR修改一下吗? ;)
> > 
> > 
> > 当然，但是我不知道你们文档的仓库在哪。我们来想提个PR的来着。😅
> 
> 哈哈哈哈哈, docs目录下. 下面两处位置.
> 
> https://github.com/version-fox/vfox/blob/main/docs/guides/quick-start.md
> 
> https://github.com/version-fox/vfox/blob/main/docs/zh-hans/guides/quick-start.md

pr在这： https://github.com/version-fox/vfox/pull/132

**Comment by aooohan** [comment]
@leihenshang 感谢贡献 ! ;)
