### ISSUE TITLE
[BUG]: Cursor not restored after interrupting `search`.

### ISSUE THREAD

**Issue by isinvon** [version-fox/vfox#131]
After using the command' vfox search xxx' and then pressing' ctrl+c', no matter what command is pressed, it will not be displayed, but the terminal can still execute any command, both wsl and window have the same problem.

https://github.com/version-fox/version-fox-plugins/assets/123001648/81110f5b-f9fe-412d-92fa-9513bd0a02a8

**Comment by aooohan** [comment]
This is caused by the cursor not being restored in time after `search` was interrupted.
