### ISSUE TITLE
[BUG]: Path of activated JDK not consistent

### ISSUE THREAD

**Issue by RumbleTumbleKid** [version-fox/vfox#134]
**Version**
0.2.6
**OS**
Windows

**Describe the bug**
When multiple JDKs are installed, launching Java will not always launch the active JDK. 
This only happens when `Invoke-Expression "$(vfox activate pwsh)"` is added to the PowerShell profile!

![WindowsTerminal_W9U1dJEJdJ](https://github.com/version-fox/vfox/assets/138381424/e3ff8e47-4d75-4220-9d1c-bb2ec22801dd)

**Comment by ahai-code** [comment]
We have refactored [the java plugin](https://github.com/version-fox/vfox-java), you can use the latest java plugin, to solve this issue.
