### ISSUE TITLE
[BUG]: Some problem...

### ISSUE THREAD

**Issue by Ive4** [version-fox/vfox#135]
**Version**
0.2.6
**OS**
Windows

**Describe the bug**
使用vfox use nodejs并且选择完版本之后报了一个错误
exec: "wmic": executable file not found in %PATH%

**Screenshots[optional]**
<img width="845" alt="image" src="https://github.com/version-fox/vfox/assets/6121465/d85b7091-e801-481f-9f41-124686b1ed45">

**Comment by aooohan** [comment]
先正确配置hook, https://vfox.lhan.me/zh-hans/guides/faq.html#%E5%88%87%E6%8D%A2xxx%E4%B8%8D%E7%94%9F%E6%95%88-vfox-use%E5%91%BD%E4%BB%A4%E4%B8%8D%E7%94%9F%E6%95%88
