### ISSUE TITLE
[Feature]: 希望可以安装多个同类插件

### ISSUE THREAD

**Issue by jingbai-code** [version-fox/vfox#139]
如题，我想安装多个 java 类的插件，比如说我 jdk8 想用 java/azul-jdk 插件，jdk17 想用 java/adoptium-jdk。
目前安装同类插件会提示插件已存在

**Comment by Chance-fyi** [comment]
可以给插件设置别名

https://vfox.lhan.me/zh-hans/usage/core-commands.html#add

**Comment by aooohan** [comment]
是的, 目前可以通过别名配置. 

后面等java插件拆分成独立仓库之后, 完全按照SDKMAN的参数形式,https://github.com/version-fox/vfox/issues/114#issuecomment-1998870109,进行实现.

`x.y.z-vendor`

**Comment by ahai-code** [comment]
可使用最新java插件.
