### ISSUE TITLE
[BUG]: The new PATH values will be lost when the Hook function is executed.

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#144]
我想起在使用过程中遇到一个问题，我在vfox挂载指令后面继续设置PATH。
```sh
eval "$(vfox activate bash)"
export PATH=$HOME/bin:$PATH
```
结果就是vfox切换版本读取`__VFOX_ORIG_PATH`环境变量是我设置PATH之前的值，这时`$HOME/bin`在PATH环境变量中被丢掉了。

如果将方案改为最开始设置临时目录，然后使用软连接切换版本就不会出现这种问题。

目前我不得不将`eval "$(vfox activate bash)"`放到最后设置PATH指令后面执行。

_Originally posted by @jan-bar in https://github.com/version-fox/vfox/issues/141#issuecomment-2017131772_

**Comment by jan-bar** [comment]
如果真要修改为软连接版本，建议创建软连接使用 [os.Symlink](https://github.com/voidint/g/blob/67e947916569ea0c0a1ad467be0138fc422a17e9/cli/install.go#L162) 这个方案。

原因可以看看 https://github.com/voidint/g/issues/51 ，我看新出的vm版本管理也没解决这个问题 [version-manager](https://github.com/gvcgo/version-manager?tab=readme-ov-file#for-windows)

**Comment by aooohan** [comment]
> 如果真要修改为软连接版本，建议创建软连接使用 [os.Symlink](https://github.com/voidint/g/blob/67e947916569ea0c0a1ad467be0138fc422a17e9/cli/install.go#L162) 这个方案。

不改成软连接方案. 还是现有方案, 能解决哈哈哈.

> 原因可以看看 [voidint/g#51](https://github.com/voidint/g/issues/51) ，我看新出的vm版本管理也没解决这个问题 [version-manager](https://github.com/gvcgo/version-manager?tab=readme-ov-file#for-windows)

哈哈哈哈, 这就出来对手了? 哈哈哈哈

**Comment by jan-bar** [comment]
是的，readme里面拿vfox做比较啊，哈哈。不过我比较喜欢软连接，路径可以短点，go会编译路径到可执行程序，所以也不想路径携带太多信息额。

**Comment by aooohan** [comment]
> 是的，readme里面拿vfox做比较啊，哈哈。不过我比较喜欢软连接，路径可以短点，go会编译路径到可执行程序，所以也不想路径携带太多信息额。不过我还是更喜欢vfox的lua脚本插件机制，更加灵活。

这项目刚4个月. 还有很多需要优化的. 一点一点来吧. 

有好的想法💡, 欢迎继续反馈!  当然, 有兴趣也可以参与进来! 😄
