### ISSUE TITLE
[BUG]: Panic on search java

### ISSUE THREAD

**Issue by subchen** [version-fox/vfox#146]
**Version**
0.2.6
**OS**
macOS

**Describe the bug**
panic on search java

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/2189657/c1477353-911c-4987-bde5-7da157f9b75d)

**Comment by bytemain** [comment]
this issue has been fixed. Please use `vfox update java` to upgrade.

https://github.com/version-fox/vfox/issues/121
