### ISSUE TITLE
[BUG]: Unable to install v8 for java/adoptium-jdk

### ISSUE THREAD

**Issue by subchen** [version-fox/vfox#148]
**Version**
0.2.6
**OS**
macOS

**Describe the bug**
```
vfox add java/adoptium-jdk
vfox search java
```

if select `v8 (LTS)` to install
then response: `no information about the current version`

if I select `v17`, I can install v17.

same issue for `vfox install java@8`

**Comment by aooohan** [comment]
I have not reproduced it. The download address corresponding to v8 is https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u402-b06/OpenJDK8U-jdk_x64_mac_hotspot_8u402b06.tar.gz

You can try to see if it can download normally, or if the download is very slow?

**Comment by subchen** [comment]
maybe I am macbook pro m2 max，it is not intel chip.

**Comment by aooohan** [comment]
> maybe I am macbook pro m2 max，it is not intel chip.

Indeed, this distribution only provides x86 for macos, nothing to do with vfox.

**Comment by subchen** [comment]
I think the plugin:available should remove unavailable versions on mac with arm chipset.

**Comment by aooohan** [comment]
> I think the plugin:available should remove unavailable versions on mac with arm chipset.

Good point. We are refactoring the plugin system, this plugin will not be maintained, and a new java plugin repository will be opened for maintenance. This enhancement will be implemented on the new repo.
