### ISSUE TITLE
[BUG]: Flutter 打包 macOS 应用时报错：no such module 'FlutterMacOS'

### ISSUE THREAD

**Issue by Sprheany** [version-fox/vfox#149]
**Version**
0.2.6
**OS**
macOS

**Describe the bug**
Flutter 打包 macOS 应用时报错：no such module 'FlutterMacOS'。经测试，Flutter 安装包中包含软链接，解压后软链接会丢失。

**Screenshots[optional]**
对比 ~/.version-fox/cache/flutter/v-3.19.3/flutter-3.19.3/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework 目录下的文件：
<img width="838" alt="截屏2024-03-26 15 36 00" src="https://github.com/version-fox/vfox/assets/7323477/a01f5d3f-b1e5-4e05-a5e0-a8978cdb92de">

**Comment by aooohan** [comment]
<img width="864" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/1d915f4a-c392-47a3-ae86-da4521ec7061">

修复了, 等下个版本吧
