### ISSUE TITLE
[BUG]: wrong java home for azul-adoptium-jdk on mac

### ISSUE THREAD

**Issue by subchen** [version-fox/vfox#150]
**Version**
0.2.6
**OS**
macOS

**Describe the bug**
vfox add java/azul-adoptium-jdk
vfox install java@8
vfox install java@17

the installed java is

`/Users/.../.version-fox/cache/java/v-8/java-8/`

No `Contents/Home` in java home.

**Screenshots[optional]**

**Comment by aooohan** [comment]
We have fixed this.  You can use `vfox update java` to upgrade to latest version to try again.
