### ISSUE TITLE
[BUG]: window下由于全局环境变量的路径分隔符引发的环境变量不被解析问题

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#153]
如下图，我查看环境变量时最后一个路径分隔符不是常规window的"\"

![image](https://github.com/version-fox/vfox/assets/14202095/0a4e74f4-67bc-484c-858d-f604aab762ee)

然后我在`cmd.exe`中发现无法解析环境变量

![image](https://github.com/version-fox/vfox/assets/14202095/45d395d8-7818-410e-b782-1c0df486fa07)

我手动改为正确的分隔符就可以

![image](https://github.com/version-fox/vfox/assets/14202095/27628c8d-6d13-47b2-8077-1364d6a8a6e0)

然后当我改成"/"时点确定window都报错了。我发现代码里面是直接通过修改注册表的方式设置环境变量，绕过了window自己的错误检测额。

![image](https://github.com/version-fox/vfox/assets/14202095/fbaacbc4-fb10-4291-a8ee-9581de10f68c)

**Comment by jan-bar** [comment]
https://github.com/version-fox/version-fox-plugins/blob/cb1e831fe40c6cc81fe0ed2b6544722ebd8984e5/golang/golang.lua#L138

刚才尝试排查时，发现lua脚本里面也存在路径分隔符问题额。

**Comment by aooohan** [comment]
> https://github.com/version-fox/version-fox-plugins/blob/cb1e831fe40c6cc81fe0ed2b6544722ebd8984e5/golang/golang.lua#L138
> 
> 刚才尝试排查时，发现lua脚本里面也存在路径分隔符问题额。

脚本这样写没什么问题, 都放在vfox里同一处理就行.

**Comment by Chance-fyi** [comment]
直接在 vfox 这层统一处理一下就行了

**Comment by jan-bar** [comment]
嗯嗯，刚看到这个改动，确实可以在window下避免路径问题。。
