### ISSUE TITLE
[BUG]: Errors may occur during plugin installation when attempting to rename across different file systems

### ISSUE THREAD

**Issue by Chance-fyi** [version-fox/vfox#156]
**Version**
main
**OS**
Linux

**Describe the bug**
`os.Rename` only works if source and destination are on the same file system.
Some information: https://stackoverflow.com/questions/73981482/moving-a-file-in-a-container-to-a-folder-that-has-a-mounted-volume-docker

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/37658940/00a4968a-13d8-4dbe-990a-c4a95d882835)

**Comment by Chance-fyi** [comment]
We can utilize the `VFOX_HOME/tmp` directory or implement a `file.Move` method.

**Comment by aooohan** [comment]
> We can utilize the `VFOX_HOME/tmp` directory or implement a `file.Move` method.

I prefer the first option.
