### ISSUE TITLE
[BUG]: add golang/golang this plugin is not compatible with current vfox (>= 0.3.0)

### ISSUE THREAD

**Issue by chenzhenjia** [version-fox/vfox#163]
**Version**
0.2.6 (latest version)
**OS**
Windows

**Describe the bug**
`vfox add golang/golang `
Checking plugin...
check failed: this plugin is not compatible with current vfox (>= 0.3.0), please upgrade vfox version to latest

**Comment by aooohan** [comment]
We are preparing 0.3.0 for release, and will be able to install it via `vfox add golang` once it is released.

**Comment by aooohan** [comment]
@chenzhenjia 0.3.0 has been released! you can use `vfox add golang` to use it now.
