### ISSUE TITLE
[BUG]: 安装python出错

### ISSUE THREAD

**Issue by 1402564807** [version-fox/vfox#166]
**Version**
vfox@0.3.0
**OS**
Windows11

**Describe the bug**

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/51551279/5f2822a2-d4cb-4fc8-9fef-5c6c9d507b42)

**Comment by aooohan** [comment]
与#49相同, 这个版本没有提供exe安装器.

**Comment by bytemain** [comment]
> 与 #49 相同, 这个版本没有提供exe安装器.

那我们可以让这个版本变成不可选，并且添加一个提示信息。

插件在返回 Available 结果的时候，可以添加一个字段:

```
disabled?: string
```

可以让这个版本不可被安装，string 就是提示信息

**Comment by bytemain** [comment]
在https://github.com/version-fox/vfox/issues/49 中追踪即可

**Comment by aooohan** [comment]
> > 与 #49 相同, 这个版本没有提供exe安装器.
> 
> 那我们可以让这个版本变成不可选，并且添加一个提示信息。
> 
> 插件在返回 Available 结果的时候，可以添加一个字段:
> 
> ```
> disabled?: string
> ```
> 
> 可以让这个版本不可被安装，string 就是提示信息

到不用这么麻烦,  插件只返回满足条件的即可.

**Comment by bytemain** [comment]
主要是考虑到会有人问，为什么列表里没有 x.x.x
