### ISSUE TITLE
[BUG]: Regression for #162

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#170]
两个问题:
1. 这个插件没有正确配置GOROOT.
2. https://github.com/version-fox/vfox/commit/22c4e5c440f59023e53d5a22519c3024e65cfd33 这次变更导致的,导致无法及时更新env. 虽然过滤了PATH, 但是把非PATH也过滤了.

_Originally posted by @aooohan in https://github.com/version-fox/vfox-golang/issues/9#issuecomment-2033386440_

**Comment by jan-bar** [comment]
改代码改出新bug了，尴尬了。应该比较所有需要设置的环境变量，全都一致时才不用重复设置是吧。

**Comment by aooohan** [comment]
> 改代码改出新bug了，尴尬了。应该比较所有需要设置的环境变量，全都一致时才不用重复设置是吧。

哈哈哈哈,小问题, 我先把这个代码删了, 后面再优化吧.

我今天先发一版,这个影响还挺大哈哈哈哈. 应该是IDEA之类的都影响.

**Comment by jan-bar** [comment]
好的，我抽空再看看怎么修复这个问题额。
