### ISSUE TITLE
[Feature]: support get all java version on search

### ISSUE THREAD

**Issue by subchen** [version-fox/vfox#174]
从 0.3.0 开始，插件系统已经重构，然后安装java 只要使用如下命令

vfox add java
vfox search java （选择指定的版本）

但是在search 过程中，默认只列出了 openjdk的并没有列出其他的，比如要查看oracle的jdk，需要
vfox search java oracle

这个就比较麻烦，而且如果不查看文档，根本就不知道有哪些版本支持。

所以建议改进search命令，默认列出所有支持的版本，或者加个什么参数控制

vfox search java --all

或者有什么命令可以查看有哪些分发版支持

比如 vfox info java 可以显示所有的分发版本。

**Comment by aooohan** [comment]
> 所以建议改进search命令，默认列出所有支持的版本，或者加个什么参数控制

我看已经有贡献者, 选择使用vfox search java all 来显示所有版本了. 

> 比如 vfox info java 可以显示所有的分发版本。

<img width="834" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/f75d762f-fcbd-401c-bc3b-d85612646759">


安装或更新插件的时候 note上有备注, 补全就行了.

刚发现,info命令, 插件改版的时候, 忘了修改了哈哈哈.
