### ISSUE TITLE
[BUG]: 执行 vfox update maven报错

### ISSUE THREAD

**Issue by mapleafly** [version-fox/vfox#176]
**Version**
0.31
**OS**
Windows11

**Describe the bug**
本机安装的0.2x版本，今天下载0.31，没有删除旧版本的情况下，直接运行setup安装新版本。

vofx list如下：

All installed sdk versions
├─┬gradle
│ └──v8.6
├─┬java
│ ├──v8
│ ├──v21
│ ├──v17
│ └──v11
└─┬maven
  └──v3.8.6

系统中安装了java、gradle和mvn 三个插件，前两个执行update成功。只有maven出现错误

执行 vfox update maven报错如下：

Checking plugin manifest...
download plugin error: Get "https://raw.githubusercontent.com/version-fox/version-fox-plugins/main/maven/maven.lua": dial tcp: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found.

**Comment by ahai-code** [comment]
@mapleafly 这似乎是网络问题，无法访问raw.githubusercontent.com，您可以百度自行解决该问题，或者直接删除maven插件后重新安装。

**Comment by aooohan** [comment]
看着像网络的问题。 卸载重新安装试试。
