### ISSUE TITLE
[Feature]: Install should install all items from .tool-versions

### ISSUE THREAD

**Issue by camflan** [version-fox/vfox#177]
#### 1. Your usage scenarios?
Ensuring that I have all required dependencies for a project and that they're up to date.

#### 2. What is your expected outcome?
`vfox install` or something like `vfox install-all` should install everything from the current `.tool-versions` file and report any plugins that are not installed. It would be great if `vfox` could also offer to install the missing plugins

**Comment by aooohan** [comment]
Good point. Are you interested in providing a PR?

**Comment by camflan** [comment]
> Good point. Are you interested in providing a PR?

I'm interested but I can't commit to it at the moment, I'll probably start tinkering soon and see where I get. If there's meaningful progress I'll let you know
