### ISSUE TITLE
[Feature]: 更多sdk支持

### ISSUE THREAD

**Issue by transtone** [version-fox/vfox#179]
https://github.com/gvcgo/version-manager/blob/main/docs/readmeCN.md#vm和vfox支持列表对比

竞争很激烈，加油！

**Comment by aooohan** [comment]
标准雷式对比法哈哈哈哈。

sdk支持只是时间问题。有新插件可以再不升级vfox的情况下直接使用。

不过也挺好，按照列表来咯。哈哈哈哈哈。

**Comment by transtone** [comment]
`在架构方面，如果你追求稳定，快速，可以选择 vmr 。如果你追求将来更多样化的插件支持，可以选择 vfox 。`  翻译一下，vfox 除了那个根本没什么插件的插件系统之外，又慢又不稳定。哈哈。
https://www.oschina.net/news/290075
