### ISSUE TITLE
[Feature]: `chezmoi cd` like command -> `vfox cd`

### ISSUE THREAD

**Issue by yeshan333** [version-fox/vfox#183]
#### 1. Your usage scenarios?

Let users know where the SDK is installed. And change shell current directory to SDK path or VFOX_HOME. Convenient to modify some configuration files.(eg: vfox config file、sdk config file, etc.)

#### 2. What is your expected outcome?

case 1:

```shell
vfox cd
# Equivalent to
cd $HOME/.version-fox
```

case 2:

```shell
vfox cd nodejs
# Equivalent to
cd $HOME/.version-fox/cache/nodejs/<current-used-version-path>
```

reference: https://www.chezmoi.io/reference/commands/cd/

**Comment by aooohan** [comment]
This should only output the SDK installation path, there is no way to switch the current directory automatically, right?

If so, I think `which` or `where` command might be better.

**Comment by yeshan333** [comment]
> This should only output the SDK installation path, there is no way to switch the current directory automatically, right?
> 
> If so, I think `which` or `where` command might be better.

In my scenario, I mainly want to modify the configuration file in VFOX_HOME(`$HOME/.version-fox`). I don't want to remember the management directory path of vofx every time and then `cd` into it. If I change the VFOX_HOME path, the workflow will become more complex.

**Comment by aooohan** [comment]
> > This should only output the SDK installation path, there is no way to switch the current directory automatically, right?
> > If so, I think `which` or `where` command might be better.
> 
> In my scenario, I mainly want to modify the configuration file in VFOX_HOME(`$HOME/.version-fox`). I don't want to remember the management directory path of vofx every time and then `cd` into it. If I change the VFOX_HOME path, the workflow will become more complex.

Ok, I got it, I don't object to this feature, you can go ahead and implement it ;)
