### ISSUE TITLE
[BUG]: flag provided but not defined

### ISSUE THREAD

**Issue by smh000809** [version-fox/vfox#184]
**Version**
0.3.1
**OS**
macOS

**Describe the bug**
flag provided but not defined

**Screenshots[optional]**
![CleanShot 2024-04-08 at 11 27 52@2x](https://github.com/version-fox/vfox/assets/85344218/a4d9d9ef-7af2-4bc9-a805-8b61f6e82cfa)

**Comment by Chance-fyi** [comment]
New version not yet released.

**Comment by Chance-fyi** [comment]
New version is available, Please update to v0.3.2
