### ISSUE TITLE
[BUG]: Set.Slice() []T Returning a reference causes deletion exceptions during loop traversal

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#186]
我在如下位置添加打印

![image](https://github.com/version-fox/vfox/assets/14202095/8dfd9fa5-509d-46ea-9a67-19201e46bf13)

结果显示pp变量会被重复遍历

![image](https://github.com/version-fox/vfox/assets/14202095/9966b93d-1431-4bf5-ad37-adf2b150eb98)

我按如下修改

![image](https://github.com/version-fox/vfox/assets/14202095/5729ad11-e601-45c5-8b85-ab903854352b)

此时应该才是正确结果

![image](https://github.com/version-fox/vfox/assets/14202095/f3aba255-52ff-4603-bbd8-acb29a3daa1b)

目测应该是for循环遍历切片引用，然后Remove内部修改了`s.elements`切片，导致for循环遍历错误

![image](https://github.com/version-fox/vfox/assets/14202095/a29bf22a-39b3-4ef7-9eed-6782e6daaa79)

**Comment by jan-bar** [comment]
我猜测 https://github.com/version-fox/vfox-golang/issues/9 ，这个问题可能也是这个原因导致的。

**Comment by aooohan** [comment]
> 我猜测 [version-fox/vfox-golang#9](https://github.com/version-fox/vfox-golang/issues/9) ，这个问题可能也是这个原因导致的。

晚点,我再试试
