### ISSUE TITLE
[BUG]: If `.tool-versions` exists in `WorkingDirectory`, `CurTmpPath`, and `HomePath` directories simultaneously, it will write multiple `PATH` entries

### ISSUE THREAD

**Issue by Chance-fyi** [version-fox/vfox#189]
**Version**
main
**OS**
Linux

**Describe the bug**
看到一个吐槽贴 https://learnku.com/articles/85977 
使用 main 分支测试时意外发现一个 Bug

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/37658940/b085ea1e-7b29-49e0-a123-fe86c8a0de2f)

![image](https://github.com/version-fox/vfox/assets/37658940/d3b26127-05c0-4aeb-b807-9de79eccfbd6)

**Comment by Chance-fyi** [comment]
好像是 install 的问题，有些版本 install 会加一条 PATH，有些版本则不会，太奇怪了

![image](https://github.com/version-fox/vfox/assets/37658940/083061a8-b488-4487-8911-a075624f2c7f)

**Comment by bytemain** [comment]
我觉得这个吐槽贴说的挺对的，现在 plugin 的命令和主要用来管理 sdk 的命令混杂起来，用起来心智负担很重，每次我都要想一下用哪个或者看一下 help

**Comment by aooohan** [comment]
> 我觉得这个吐槽贴说的挺对的，现在 plugin 的命令和主要用来管理 sdk 的命令混杂起来，用起来心智负担很重，每次我都要想一下用哪个或者看一下 help

插件的:
- `vfox add `
- `vfox info`
- `vfox update`
- `vfox remove`
- `vfox avaiable`

sdk的:
- `vfox install`
- `vfox use`
- `vfox search`
- `vfox uninstall`
- `vfox list`
- `vfox current`

我还是没明白为啥会混.  一开始确实想过在plugin命令前面加个plugin, 例如 `vfox plugin add nodejs`, 但是我嫌太长了命令.

**Comment by jan-bar** [comment]
![image](https://github.com/version-fox/vfox/assets/14202095/7878a3e1-f88e-462e-aca3-719ac8a3cd7c)

当初我看到这个，内心震撼，相当炸裂。`nodejs`的用户有这种疑惑，我表示不意外。毕竟`npm`/`yarn`/`pnpm`包管理工具各有各的想法，而且我看`pnpm`文档，可以设置`pnpm`自己的包管理路径，就这意思是不想和`npm`/`node`一起切换的样子。

就连`js`运行时都有3个：[nodejs](https://github.com/nodejs/node)，[deno](https://github.com/denoland/deno)，[bun](https://github.com/oven-sh/bun)

我只用了`nodejs`，另外两个没研究，不过估计也是各种不一致，需要区分命令啥的。前端太难学的，我还是继续`go`吧，😄😄😄

**Comment by aooohan** [comment]
> 当初我看到这个，内心震撼，相当炸裂。`nodejs`的用户有这种疑惑，我表示不意外。毕竟`npm`/`yarn`/`pnpm`包管理工具各有各的想法，而且我看`pnpm`文档，可以设置`pnpm`自己的包管理路径，就这意思是不想和`npm`/`node`一起切换的样子。

我搞这个项目的初心就是因为, 我即 使用nvm又使用sdkman. 并且macos和windows有时来回切. 每个工具基本上命令都不一致真的很糟心. 😂😂

**Comment by bytemain** [comment]
> 我还是没明白为啥会混. 一开始确实想过在plugin命令前面加个plugin, 例如 `vfox plugin add nodejs`, 但是我嫌太长了命令.

可能因为你是开发者，你知道所有命令的作用，对于新手来说，他不知道有哪些命令。

add 和 install

remove 和 uninstall

list 和 available

这都是相近的单词

**Comment by aooohan** [comment]
> add 和 install
> 
> remove 和 uninstall
> 
> list 和 available
> 
> 这都是相近的单词

那目前看, 只能加前缀了. `vfox plugin add/remove/update/available nodejs`.

而且这些命令已经存在很久了, 只能两则都共存了.

**Comment by bytemain** [comment]
这个再看反馈吧，感觉也不急着做

**Comment by subchen** [comment]
感觉命令没啥问题，不容易混淆。

但是概念的定义还有点不清晰。

比如 plugin 的叫法，不好理解，建议改成 repo 或者 source

而 sdk 这个定义没问题。
