### ISSUE TITLE
[BUG]: vfox install java@8以上版本报错

### ISSUE THREAD

**Issue by c0febean** [version-fox/vfox#198]
**Version**
0.3.1 非该版本特有
**OS**
Linux

**Describe the bug**
安装8以上jdk版本报错
解压异常未找到文件夹
unpack failed, err:symlink ../java.base/ADDITIONAL_LICENSE_INFO /home/c0febean/.version-fox/cache/java/v-21.0.2+13/java-21.0.2+13/legal/java.compiler/ADDITIONAL_LICENSE_INFO: no such file or directory

----

经排查, 解压jdk.tar.gz 时, 因代码问题, 软链文件的所在文件夹没有被创建, 导致软链文件解压异常

**Screenshots[optional]**
![Snipaste_2024-04-11_20-18-36](https://github.com/version-fox/vfox/assets/52570897/4c039d76-5b16-4c99-9ba0-fb65aab9dfac)

**Comment by aooohan** [comment]
感谢反馈, 以及提供的PR.
