### ISSUE TITLE
[Feature]: If no version number provided,  provide a prompt to show available sdk version

### ISSUE THREAD

**Issue by bytemain** [version-fox/vfox#205]
#### 1. Your usage scenarios?

install golang by:

```sh
➜  ~ vfox install golang
plugin [PreInstall] method error: no version number provided
```

and we can provide a prompt:
```
➜  ~ vfox install golang
> no version number provided, do you want to search available versions and install it? (y/n)
y
Please select a version of golang [type to search]: 
->  v1.22.1 (stable)
   v1.21.8 (stable)
   v1.22.0
   v1.21.7
   v1.21.6
   v1.21.5
   v1.21.4
   v1.21.3
   v1.21.2
   v1.21.1
   v1.21.0
   v1.22rc2
   v1.22rc1
   v1.21rc4
   v1.21rc3
   v1.21rc2
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
```

- https://github.com/version-fox/vfox-golang/issues/8

close: https://github.com/version-fox/vfox-nodejs/issues/8

#### 2. What is your expected outcome?

**Comment by aooohan** [comment]
<img width="1577" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/dec10678-453b-4049-b74c-0da3e08764b5">

It doesn't seem to have really been fixed.

**Comment by aooohan** [comment]
I see that it is the existence of the version returned by the `PreInstall` that determines whether or not to display the available list. But it's possible that `PreInstall` has already thrown an error.

https://github.com/version-fox/vfox/blob/350e67a8bb4171211c0193d15320bdb3032469e9/cmd/commands/install.go#L85-L88

https://github.com/version-fox/vfox/blob/350e67a8bb4171211c0193d15320bdb3032469e9/internal/interfaces.go#L112-L114

For example, `erlang` plugin:

https://github.com/version-fox/vfox-erlang/blob/afa9f2cc5e00788894bf51bb7cac9fcb71c444bc/hooks/pre_install.lua#L13-L16

**Comment by aooohan** [comment]
I now think it might be better to solve it in the following two ways:
1. If no version provided, we will pass `latest` as version to the plugin, and we must ask the plugin to implement the meaning of `latest`.
2. We still treat it as the latest and use the version first result from `search`. But we must ask the plugin to sort the Available results in descending order.
