### ISSUE TITLE
[Feature]: vfox use fuzzy matching version number

### ISSUE THREAD

**Issue by cifaz** [version-fox/vfox#210]
#### 1. Your usage scenarios?
vfox use java@22
不管是安装几个版本, 都会出现
```
java@v22+36 is not installed
```

#### 2. What is your expected outcome?
1. 建议使用时, 如果只安装一个版本, 版本号完全模糊匹配,
2. 安装多个版本时, 以大版本为基础默认匹配第一个; 以方便快速使用和切换;

**Comment by Chance-fyi** [comment]
这个功能可以通过插件的 PreUse 函数实现

**Comment by aooohan** [comment]
> 不过如果插件未实现 PreUse 函数，vfox 端或许也可以做一个默认的处理

好主意, 如果没有实现PreUse, 就默认前缀匹配已安装版本的第一个.
