### ISSUE TITLE
[BUG]: Unexpected behavior when repeat install via version alias

### ISSUE THREAD

**Issue by yanecc** [version-fox/vfox#214]
当重复安装某个版本的sdk，
https://github.com/version-fox/vfox/blob/768ce6a906aadef9f50754412708680218bb02e7/internal/sdk.go#L53-L56
vfox会比较命令vfox install sdk@version中@后面的版本的目标安装路径是否存在
https://github.com/version-fox/vfox/blob/768ce6a906aadef9f50754412708680218bb02e7/cmd/commands/install.go#L34-L61
若存在，我们能够直接得到返回。

使用插件的PreInstall hook，可以设置某个版本的别名
通过别名安装以后，安装的路径为实际版本路径

因此，当再次使用别名重复安装，vfox会删除已经安装的实际版本路径
https://github.com/version-fox/vfox/blob/768ce6a906aadef9f50754412708680218bb02e7/internal/sdk.go#L80-L85
这不符合预期。

可以看出vfox有关于别名安装的考虑
https://github.com/version-fox/vfox/blob/768ce6a906aadef9f50754412708680218bb02e7/internal/sdk.go#L86-L91
此判断应提前，并在删除实际安装路径之前返回

**Comment by aooohan** [comment]
> 此判断应提前，并在删除实际安装路径之前返回

感谢反馈, 确实是bug, 你说的修复方式也正确,  有兴趣提个PR吗?
