### ISSUE TITLE
[BUG]: Wrong behavior about plugin alias and something to be improved

### ISSUE THREAD

**Issue by yanecc** [version-fox/vfox#218]
**Describe the bug**
 1. 以相同别名安装不同插件后，会下载插件，但是安装失败
预期：不下载插件
2. 以别名安装某插件后，可以直接安装或使用其他别名安装该插件；但是直接安装某插件以后，无法再用别名安装该插件
预期：以不同名称添加的插件应视作不同插件，只要别名不与已安装插件名称重复即可安装
3. 对旧版本插件名称格式`<category>/<plugin-name>`的兼容仅对官方网址生效
预期：与网址无关，应对任何网址生效

**Comment by yanecc** [comment]
我发现还有一些问题需要确定，
例如，目前当使用别名kt安装了kotlin插件，我们仍需要使用
```
vfox search kotlin
```
来获取可用版本，而不是
```
vfox search kt
```
这是需要解决的问题。

vfox有提到
https://github.com/version-fox/vfox/blob/4cf47df6609f3fd86b51e832300685418ef819a6/docs/guides/faq.md?plain=1#L20

所以应该如何正确对待插件名称？@aooohan
1. 将使用不同名称添加的插件视作不同插件
2. 无论是否使用别名，同一插件仅允许添加一次

**Comment by aooohan** [comment]
按照你现在的处理, 我觉得也不错. 弱化了插件自身的名字, 以插件索引仓库和用户输入的别名为准.  👍

**Comment by aooohan** [comment]
已处理, 感谢贡献!
