### ISSUE TITLE
[Feature]: Add ctx.name to AvailableHook

### ISSUE THREAD

**Issue by yanecc** [version-fox/vfox#221]
#### 1. Your usage scenarios?

在我的插件中，我希望用户按需自行修改文件的某些内容，需要指引插件路径

``` lua
return {
    -- Authenticate to get higher rate limit
    githubToken = os.getenv("GITHUB_TOKEN") or "",
```

#### 2. What is your expected outcome?

由于插件名称不确定，硬编码并不适宜，应该允许插件作者使用插件实际安装的名称，以更好地指引用户。

**Comment by aooohan** [comment]
我想你需要的是这个。

https://github.com/version-fox/vfox-plugin-template/blob/main/Injection.lua#L15

**Comment by yanecc** [comment]
> 我想你需要的是这个。
> 
> https://github.com/version-fox/vfox-plugin-template/blob/main/Injection.lua#L15

好的，这对我来说足够了
