### ISSUE TITLE
[BUG]: vfox use java指令异常

### ISSUE THREAD

**Issue by ctyytc** [version-fox/vfox#225]
**Version**
vfox version 0.4.0

**OS**
macOS 14.4.1

**Describe the bug**
我通过java插件，安装了2个JDK17版本，openjdk（v17.0.2+8）和zulu（v17.0.11+9-zulu），排序上openjdk优先，目前发现：

在使用use命令（vfox use java@17.0.11+9-zulu）时会出现：
`java@ is not installed`

在使用use命令（vfox use java）从列表中选择一个版本时会出现：
`java@ is not installed`

在使用use命令（vfox use java@17）时会出现：
`Now using java@17.0.2+8`

发现use命令没法再用精确版本号来指定JDK

**Screenshots[optional]**
<img width="448" alt="image" src="https://github.com/version-fox/vfox/assets/413886/32d1e497-a910-4208-bf52-22fb2a63b12f">
<img width="316" alt="image" src="https://github.com/version-fox/vfox/assets/413886/34c84faf-e831-4f44-9315-2db46ac413c8">
<img width="241" alt="image" src="https://github.com/version-fox/vfox/assets/413886/ef849c8b-580f-4b38-97dc-2eb475cf898f">
<img width="265" alt="image" src="https://github.com/version-fox/vfox/assets/413886/6aef226c-b840-427b-9c1d-7ef18993b697">

**Comment by aooohan** [comment]
已知问题, 看#224

稍后我会再发一版

**Comment by aooohan** [comment]
0.4.1已发, 感谢反馈.
