### ISSUE TITLE
[BUG]: install.sh文件bug

### ISSUE THREAD

**Issue by CoderConan** [version-fox/vfox#237]
**Version**
v0.4.1
**OS**
macOS

**Describe the bug**
根据官网提供的安装命令，执行后安装不成功。
看了一下脚本内容，脚本中未判断目录/usr/local/bin是否存在，如果/usr/local下没有bin目录，mv会将目标当作文件处理，将文件vfox重命名为/usr/local/bin文件。
https://github.com/version-fox/vfox/blob/b3f9c957ef0d96fdafca62b8b881bed556b8f473/install.sh#L52

**Screenshots**
![image](https://github.com/version-fox/vfox/assets/88372830/58b87171-7a17-44ba-b8f5-9c4d2e20574d)

**Comment by aooohan** [comment]
有兴趣提个PR吗 ;)

**Comment by CoderConan** [comment]
> 有兴趣提个PR吗 ;)

https://github.com/version-fox/vfox/pull/241
