### ISSUE TITLE
[Feature]: 希望可以更改安装包位置，更换SDK到非系统盘

### ISSUE THREAD

**Issue by jkxbest** [version-fox/vfox#249]
未来可能如nvm一样，在安装时选择位置和SDK位置，或者压缩包里给一个配置文件可以更改SDK存放位置，毕竟放在非系统盘统一管理更方便。

**Comment by aooohan** [comment]
目前支持更改.

https://vfox.lhan.me/zh-hans/guides/configuration.html#%E5%AD%98%E5%82%A8%E8%B7%AF%E5%BE%84
