### ISSUE TITLE
[BUG]: 无法正确切换软件版本

### ISSUE THREAD

**Issue by lakako** [version-fox/vfox#251]
**Version**
The version you are currently using
**OS**
Windows

**Describe the bug**

使用scoop安装了java17

路径结构

/A 
/B

在A路径下执行vfox use -p java@8

执行java -version 显示为java8

cd 到B路径
执行java -version 还是显示为java8

正常来说应该是java17

vfox版本 0.4.2

**Comment by aooohan** [comment]
这跟vfox的策略有关.

当前的 vfox 策略是，如果在项目（project/.tool-versions）中有 .tool-version 文件，则无论是否切换目录，当前 shell 都将使用该版本，直到遇到下一个 .tool-versions 文件或手动执行 vfox use 命令时，版本才会改变。

https://github.com/version-fox/vfox/issues/228#issuecomment-2071470614

**Comment by lakako** [comment]
感觉这个逻辑不太对。。不过也行
