### ISSUE TITLE
[BUG]: Failed to switch environment in external bash script file

### ISSUE THREAD

**Issue by ZhengQinyu** [version-fox/vfox#253]
**Version**
0.4.2
**OS**
Linux

**Describe the bug**
在bash脚本中使用 vfox use -s java@17.0.2+8，打印出来还是之前版本的jdk

## 默认版本
![image](https://github.com/version-fox/vfox/assets/11704766/a1908d7c-404b-4f88-8603-9bc4d5cf732e)

## 创建一个demo.sh脚本，内容如下
![image](https://github.com/version-fox/vfox/assets/11704766/fb989b42-a38a-43c7-a8d2-d09ddc17cfb9)
打印结果如下，没有成功切换版本

![image](https://github.com/version-fox/vfox/assets/11704766/17ca22ee-f277-4922-b8f4-4e047b372ec5)

**Comment by aooohan** [comment]
因为vfox的机制是利用shell hook进行刷新.  你这么写shell是不会执行hook的. 所以需要手动刷新一下. 

参考下面的配置.

https://github.com/version-fox/vfox-php/blob/ab95a5a317c6e5f7fc9e8622c3978c14d890ce35/.github/workflows/test-linux.yaml#L34-L37

**Comment by ZhengQinyu** [comment]
我需要的功能是：在shell脚本中切换jdk版本，进行不同java项目的打包。我以为这种需求应该很常用吧？

**Comment by ZhengQinyu** [comment]
手动刷新是可以了，但是总感觉有些麻烦。
![image](https://github.com/version-fox/vfox/assets/11704766/14729890-b68f-455f-ba5a-9100cc8e77cc)
打印结果
![image](https://github.com/version-fox/vfox/assets/11704766/73d454a5-0fc6-4fe7-946f-8136c24ebaac)

**Comment by ZhengQinyu** [comment]
手动刷新是可以的，但是感觉有些麻烦。

![image](https://github.com/version-fox/vfox/assets/11704766/ca9f4e3d-3e09-4820-a56d-27477b11801f)

![image](https://github.com/version-fox/vfox/assets/11704766/4289038a-4b96-4847-80f1-1d4ee0d82530)

**Comment by aooohan** [comment]
> 我需要的功能是：在shell脚本中切换jdk版本，进行不同java项目的打包。我以为这种需求应该很常用吧？

是的, 有解决方案了. 0.5.0下个版本修复.
