### ISSUE TITLE
[BUG]: Set storage.sdkPath via CLI regression

### ISSUE THREAD

**Issue by ccavolt** [version-fox/vfox#268]
**Version**
0.5.1
**OS**
Linux

**Describe the bug**
Prior to 0.5.1, "vfox config storage.sdkPath ${INSERT_PATH_HERE}" worked as expected. Now it errors with "unsupported configuration type".

**Screenshots[optional]**
<img width="322" alt="image" src="https://github.com/version-fox/vfox/assets/10134274/7a2bcf53-ac44-4eee-8567-6ca5339a484b">

**Comment by Chance-fyi** [comment]
Oops, I missed the string type.

**Comment by ccavolt** [comment]
Thanks for fixing this so quickly! Will you be building a new release for it soon?

**Comment by aooohan** [comment]
> Thanks for fixing this so quickly! Will you be building a new release for it soon?

It's coming. ;)

**Comment by ccavolt** [comment]
Indeed. Thank you so much for that and for building this great piece of software!
