### ISSUE TITLE
[Feature]: 可选择实现的 pin 命令

### ISSUE THREAD

**Issue by devbean** [version-fox/vfox#271]
#### 1. Your usage scenarios?
Volta 提供了一种 pin 命令，可以在 package.json 中记录下本项目使用的 nodejs 的版本号。在切换不同的项目时，Volta 可以自动安装项目所需版本号，并且自动切换到对应的版本。

#### 2. What is your expected outcome?
虽然 vfox 提供了项目级的版本管理能力，但如果能够自动切换会更方便，并且该版本号可以提交到 git 中，以便与他人共享。有没有可能实现类似的功能？初步设想，该功能应该在插件中可**选择实现**类似 pin 的命令。如果插件支持 pin 命令，比如 nodejs，则在 package.json 中进行记录（类型 volta 的实现）；如果是 java，则可以看是否存在 pom.xml 或其它配置文件。

**Comment by aooohan** [comment]
`vfox use -p nodejs` 会在当前项目下生成`.tool-versions`文件, 会锁定版本的. 这个满足不了吗?

**Comment by devbean** [comment]
测试了一下，感觉应该是可以的，感谢回复
