### ISSUE TITLE
[Feature]: Do not print and set environment variables when there is no need to set environment variables when executing vfox env -s xxx

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#273]
#### 1. Your usage scenarios?

When there is no need to set environment variables and you don’t want the terminal to set environment variables every time you execute a command

#### 2. What is your expected outcome?

![image](https://github.com/version-fox/vfox/assets/14202095/dffdb533-08ed-4609-b66c-584a7d10df2a)

Is it possible to achieve this function by changing the code in the picture above? I’m not sure if there will be bugs after the modification.

**Comment by aooohan** [comment]
> Is it possible to achieve this function by changing the code in the picture above?

This change is a bit complicated, we just need to determine if `sdkCurrentPaths` is empty as now only  `PATH` is repeat setting.

https://github.com/version-fox/vfox/blob/099640e4783d0d53edb02d5f31d5909f61a4a202/cmd/commands/env.go#L132
