### ISSUE TITLE
[Feature]: Consistent list outputs

### ISSUE THREAD

**Issue by rgustafson-ie** [version-fox/vfox#277]
#### 1. Your usage scenarios?

Using version 0.5.2.  Running commands that list output, such as `vfox list` or `vfox current`, and trying to visually interpret the output.  Currently the ordering appears to randomly vary.

#### 2. What is your expected outcome?

To ease comprehension, the output should be consistently ordered (e.g. alphabetical) for the subcommand, and ideally consistent across subcommands. 

For example, two runs of `vfox current`:
```
vfox current
java -> N/A 
maven -> N/A 
nodejs -> N/A 
python -> N/A 

vfox current
python -> N/A 
java -> N/A 
maven -> N/A 
nodejs -> N/A 
```

**Comment by aooohan** [comment]
We can sort them in alphabetical order.

**Comment by mchgood** [comment]
Hello, I am very interested in this issue and would like to claim it for resolution. Could you please assign it to me?

**Comment by Chance-fyi** [comment]
@mchgood Hi, I'm glad you're interested in solving it. I've assigned it to you.

**Comment by ccavolt** [comment]
Will this also fix the random reordering that occurs in .tool-versions when rebuilding a devcontainer? The versions don't change, just for example if I have elixir and erlang installed, sometimes erlang will be on top, sometimes elixir. I can create a separate issue if this isn't related.

**Comment by mchgood** [comment]
> Will this also fix the random reordering that occurs in .tool-versions when rebuilding a devcontainer? The versions don't change, just for example if I have elixir and erlang installed, sometimes erlang will be on top, sometimes elixir. I can create a separate issue if this isn't related.这也将修复中发生的随机重新排序。重建devcontainer时的工具版本？版本不会改变，例如，如果我安装了elixir和erlang，有时erlang会在上面，有时elixir。我可以创建一个单独的问题，如果这不是相关的。

I think this issue has already been fixed

**Comment by Chance-fyi** [comment]
> Will this also fix the random reordering that occurs in .tool-versions when rebuilding a devcontainer? The versions don't change, just for example if I have elixir and erlang installed, sometimes erlang will be on top, sometimes elixir. I can create a separate issue if this isn't related.

@ccavolt You caught me! I noticed this, but I thought it wasn't a frequent operation, so I didn't mention it. Haha.

> I think this issue has already been fixed

@mchgood It's not resolved yet. The code related to this functionality is here.

https://github.com/version-fox/vfox/blob/2d15fc8bccd84989f73300732c8d1b8d6018a57f/cmd/commands/install.go#L200-L221

**Comment by aooohan** [comment]
> The code related to this functionality is here.

No.  The problem should be here, the `FileRecord` is use `map` to record something which lead to random sorting.


https://github.com/version-fox/vfox/blob/2d15fc8bccd84989f73300732c8d1b8d6018a57f/internal/toolset/file_record.go#L28-L32
