### ISSUE TITLE
[BUG]: Java sdk 安装后切换，无法使用

### ISSUE THREAD

**Issue by zhao-wuyan** [version-fox/vfox#278]
**Version**
vfox version 0.5.2
**OS**
Windows

**Describe the bug**
我清理了以前安装的jdk，然后用vfox安装。但是无法直接使用。是需要自己配置环境变量吗。我看了系统环境变量并没有自动配置上去

**Screenshots[optional]**
![Clip_2024-05-18_16-37-16](https://github.com/version-fox/vfox/assets/59789646/a6a89a92-7e6c-4b29-bbd5-299615c0acbb)

**Comment by aooohan** [comment]
已知问题, 下个版本修复, 建议先用0.4.x版本.

version-fox/vfox-java#16

**Comment by SALIMMOASIN** [comment]
> **Version**
> 
> vfox version 0.5.2
> 
> **OS**
> 
> Windows
> 
> 
> 
> **Describe the bug**
> 
> 我清理了以前安装的jdk，然后用vfox安装。但是无法直接使用。是需要自己配置环境变量吗。我看了系统环境变量并没有自动配置上去
> 
> 
> 
> **Screenshots[optional]**
> 
> ![Clip_2024-05-18_16-37-16](https://github.com/version-fox/vfox/assets/59789646/a6a89a92-7e6c-4b29-bbd5-299615c0acbb)
> 
>
