### ISSUE TITLE
Why Gradle download so slow in china

### ISSUE THREAD

**Issue by dokcn** [version-fox/vfox#279]
**Version**
The version you are currently using: 0.5.3

**OS**
Ubuntu 24.04 LTS 6.8.0-31-generic
using Aliyun ECS

**Question Description**
as the title says

Plugin Info:
Name     -> gradle
Version  -> 0.1.1
Homepage -> https://github.com/version-fox/vfox-gradle

![Snipaste_2024-05-18_23-03-58](https://github.com/version-fox/vfox/assets/24841978/e42a79a5-740c-4116-927b-46159d295529)

**Comment by aooohan** [comment]
You need to check your network, the plugin uses the official address.

https://github.com/version-fox/vfox-gradle/blob/6aa59abec80f63f821a704baf731cbb39b1111d9/lib/util.lua#L6-L8

**Comment by dokcn** [comment]
gradle plugin can use a mirror to speed up download by adding a system environment variable called VFOX_GRADLE_MIRRORS
