### ISSUE TITLE
[BUG]: Executing vfox env --cleanup will delete the directory link created during initialization

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#280]
**Version**
0.5.3
**OS**
Windows

**Describe the bug**
# clink
As shown in the figure below, when starting the terminal, the temporary directory does not have 4 sdk directory links.

![image](https://github.com/version-fox/vfox/assets/14202095/bacdc9a9-bdc9-434c-aaf1-9330a2b7ab07)

https://github.com/version-fox/vfox/blob/3c0bff01085780b97bb818ecc9845b95feea52f3/internal/shell/clink_vfox.lua#L119-L125

When clink is started again after deleting 122 lines of code, the correct result is obtained.

![image](https://github.com/version-fox/vfox/assets/14202095/2acfa279-8e3e-43bd-b889-abc6bba9534e)

I noticed that only `vfox env --cleanup` will be executed here

# powershell
I tested powershell at the same time. As shown in the figure below, there are also three missing sdk directory links.

![image](https://github.com/version-fox/vfox/assets/14202095/fefeaa9a-3d3f-416f-9f14-eec57b422cd5)

https://github.com/version-fox/vfox/blob/3c0bff01085780b97bb818ecc9845b95feea52f3/internal/shell/powershell.go#L35-L39

After I delete the 38 line of code and test it again with powershell, there should be no problem.

![image](https://github.com/version-fox/vfox/assets/14202095/149dc69a-736f-4e66-835b-4a069fa1cf66)

**Comment by aooohan** [comment]
Normally `env --cleanup` is executed when the shell exits, but unfortunately `Powershell` is not supported.


It's easy to fix, just delete the following line.

https://github.com/version-fox/vfox/blob/3c0bff01085780b97bb818ecc9845b95feea52f3/internal/manager.go#L597

**Comment by jan-bar** [comment]
> Normally `env --cleanup` is executed when the shell exits, but unfortunately `Powershell` is not supported.

`Clink` does not support it either

Monitoring the exit of the terminal is unreliable. It is difficult to monitor if the computer shuts down or restarts and exits abnormally.

I saw that the temporary directory carries the process pid, and it is more reliable to clean up the temporary directory of the process pid that does not exist in the current system.

**Comment by aooohan** [comment]
> `Clink` does not support it either

: <
> 
> Monitoring the exit of the terminal is unreliable. It is difficult to monitor if the computer shuts down or restarts and exits abnormally.
Yes.
> 
> I saw that the temporary directory carries the process pid, and it is more reliable to clean up the temporary directory of the process pid that does not exist in the current system.

The current logical includes two parts:
1. clear all temporary files before the current day.
2. clear all temporary files of the current shell.

But for now, we just need to keep 1).
