### ISSUE TITLE
[BUG]: Creating a new terminal across the day cleans the temporary directory, causing the directory link in use to be deleted

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#283]
**Version**
0.5.3
**OS**
Windows

**Describe the bug**
`1716134400` -> `2024-05-20 00:00:00`，`1716220800` -> `2024-05-21 00:00:00`

The terminal created on `2024-05-20` never exits

Create a new terminal on `2024-05-21` to trigger the temporary directory cleanup logic

Then the temporary directory used by the terminal created on `2024-05-20` was deleted, and the temporary directory of `2024-05-21` was generated. However, the terminal did not switch to the new temporary directory, and the corresponding temporary directory was not created directory link

![image](https://github.com/version-fox/vfox/assets/14202095/9cdec9e5-008b-4a62-8659-05f2d2cd9f43)

**Comment by aooohan** [comment]
> The terminal created on 2024-05-20 never exits

This situation was never considered from the beginning. : |

If we want to solve this issue, we have to see if the process is still alive as you suggested before we clean up.

https://github.com/version-fox/vfox/issues/280#issuecomment-2119853205

**Comment by jan-bar** [comment]
> If we want to solve this issue, we have to see if the process is still alive as you suggested before we clean up.

This solution needs to support cross-platform detection of whether the pid is running, which is not easy to implement.

According to the above situation, when the terminal executes `vfox env -s xxx` , a new temporary directory will be created, but the relevant directory link is missing in the directory. And the environment variables are not updated to the new temporary directory.

Add cross-day detection to the `vfox env -s xxx` command. When a cross-day occurs, a new temporary directory will be generated and new environment variables will take effect. What about this solution?

**Comment by jan-bar** [comment]
> If we want to solve this issue, we have to see if the process is still alive as you suggested before we clean up.

This library can find the currently running process：https://github.com/mitchellh/go-ps

**Comment by ZuBB** [comment]
hey guys,

Is it possible that this issue still exists somehow/partially? today I faced a case when npm suddenly became unavailable (kitty+tmux+fish). I created a new tab in tmux, and there npm/node was present. then I back to the previous tab and npm here resurrected.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/3564b6c7-b99b-410e-b74b-1bde8f21ecde">

**Comment by jan-bar** [comment]
@ZuBB

Run `which node` to see which directory the node is in. It may be in: https://vfox.lhan.me/usage/shims-path.html

**Comment by ZuBB** [comment]
just got this one more time

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/5c31adcd-0f1e-4800-9e66-a8b6c95004e6">
