### ISSUE TITLE
[BUG]: Java installed by vfox cannot be used normally

### ISSUE THREAD

**Issue by Wn16h7** [version-fox/vfox#286]
**Version**
vfox： 0.5.2
**OS**
Windows

**Describe the bug**
The Java installed by vfox cannot be used normally. I have tried various versions of Oracle and Zulu such as 8, 11, and 17.

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/105099466/3f888806-ad14-47a9-a13e-b915a1d37862)
![image](https://github.com/version-fox/vfox/assets/105099466/5226acdd-c4e1-44d5-a0dd-8f69c6543b7c)
![image](https://github.com/version-fox/vfox/assets/105099466/d54af35a-4383-4975-bf96-9ba8a597a831)
![image](https://github.com/version-fox/vfox/assets/105099466/c6d268b0-5fb4-48e9-98f2-e1f18a1716fe)

**Comment by Wn16h7** [comment]
Error: opening registry key 'Software\JavaSoft\Java Runtime Environment'
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

I tried the method provided by https://stackoverflow.com/questions/6362037/java-error-opening-registry-key, but I did not install additional java independently

**Comment by aooohan** [comment]
升级到最新.

https://github.com/version-fox/vfox-java/issues/16

**Comment by Wn16h7** [comment]
感谢，我使用winget安装的，以为是最新版

> 升级到最新.
> 
> [version-fox/vfox-java#16](https://github.com/version-fox/vfox-java/issues/16)
