### ISSUE TITLE
Bitteube rprufenSiediemarkiertenFelder

### ISSUE THREAD

**Issue by SALIMMOASIN** [version-fox/vfox#29]
**Version**
The version you are currently using
**OS**
macOS、Linux、Windows

**Describe the bug**

**Screenshots[optional]**

**Comment by SALIMMOASIN** [comment]
https://github.com/version-fox/vfox/issues/29#issue-2097329389

**Comment by aooohan** [comment]
@SALIMMOASIN Please do not raise meaningless issues at will.
