### ISSUE TITLE
Background process running after vfox use

### ISSUE THREAD

**Issue by tsmgodoi** [version-fox/vfox#291]
**Version**
0.5.3
**OS**
Windows (Git Bash)

**Describe the bug**
After I run `vfox use nodejs@<version>` on a Git Bash on Windows, it seems a background vfox process starts running. So when I try to close the Git Bash Window, it always prompt me if I want to close it anyway. Is it the way it works? Is it really required to run this background process? I'm not suspicious about this process, but it's anoying every time I want to close the Git Bash window I have to accept this prompt. By the way, when I run this command I've got the warning `Warning: The current shell lacks hook support or configuration. It has switched to global scope automatically.`

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/14880633/8574a0d3-7160-406b-a003-5cf3179089fc)

**Comment by aooohan** [comment]
Please see: https://vfox.lhan.me/guides/faq.html#switch-xxx-not-work-or-the-vfox-use-command-does-not-work

**Comment by tsmgodoi** [comment]
It worked! Thank you!
