### ISSUE TITLE
[BUG]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by iamdzk** [version-fox/vfox#295]
**Version**
0.5.3
**OS**
Windows

**Describe the bug**
安装0.5.3之后运行报错，我重新安装0.5.2，错误就会消失，报错信息请看截图

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/58968475/11afdabc-54f1-4c7f-8a8a-3c3b1cff275c)

**Comment by wen-carl** [comment]
0.6.10 same issue
