### ISSUE TITLE
[BUG]: 目录自动映射问题

### ISSUE THREAD

**Issue by JustTestCode** [version-fox/vfox#298]
**Version**
0.5.3
**OS**
Windows

**Describe the bug**
打开一个新控制台 创建的目录
```C:\Users\abc\.version-fox\temp\1717344000-12372```
不会自动junction进行映射目录，整个目录下就一个文件flush_env.cache
每次都要重新 use一下环境才会创建目录映射，这样导致 goland 有问题，其他环境我还没测试
执行go env命令
```
go: cannot find GOROOT directory: C:\Users\abc\.version-fox\temp\1717344000-23912\golang
```
按说不是应该自动映射的吗？每次这样 我都还要重新 vfox use  golang一下才行
安装的时候已经使用了 ```vfox use -g golang@1.22.3```

**Comment by jan-bar** [comment]
已经在 https://github.com/version-fox/vfox/issues/280 修复，只是没有发布最新版。你可以 `go install github.com/version-fox/vfox@9bcc064` 编译最新代码再试试看。

**Comment by noble-gase** [comment]
安装了最新版本，根本就没解决
