### ISSUE TITLE
[Question] vfox 搭配 vscode 使用有什么最佳实践吗

### ISSUE THREAD

**Issue by bitxeno** [version-fox/vfox#299]
**Version**
vfox version 0.5.3

**OS**
macOS

**Question Description**
vfox 已经设置全局使用了，使用`vfox current`查看版本也是正确的，但打开 vscode 总是获取系统的版本，不是 vfox 全局指定的版本

**Comment by xinlingqudongX** [comment]
在安装文档下面不是还要执行一个脚本吗，那个需要执行吧

**Comment by bitxeno** [comment]
> 在安装文档下面不是还要执行一个脚本吗，那个需要执行吧

bashrc有加脚本，但有时不生效，不知什么原因，我再查下
