### ISSUE TITLE
powershell7中无法识别环境变量、且有乱码现象

### ISSUE THREAD

**Issue by greesBird** [version-fox/vfox#302]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
vfox 0.5.3, powershell7

**OS**
Windows11

**Question Description**
将vfox挂载到powershell7中后，sdk无法识别环境变量，且有乱码现象, 如下图所示
![image](https://github.com/version-fox/vfox/assets/19472174/bac20100-b40a-432a-ab97-9045df1733b6)

取消挂载后，上述现象消失，恢复正常，如下图所示
![image](https://github.com/version-fox/vfox/assets/19472174/1cd0d486-4a6c-44be-a88e-78864f2a8652)

**Comment by ieayoio** [comment]
我之前和你有一样的问题，今天突然发现问题消失了，和你分享下我当时的情况：

我怀疑问题可能和[一次修复](https://github.com/version-fox/vfox/pull/117)有关，OutputEncoding被改为UTF8导致的，java8在windows下好像是GBK的，当我是用vfox切换到java17时，乱码问题消失了

于是我使用`code $profile`用vscode编辑，在末尾添加下面的代码后，java8下问题也消失了
```
$OutputEncoding = [System.Text.Encoding]::GetEncoding("GBK")
[console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("GBK")
[console]::InputEncoding = [System.Text.Encoding]::GetEncoding("GBK")
```
但是我不想用GBK

当时经过我的一番折腾，问题还是没有彻底解决，我就搁置了这个问题
今天看到你的反馈时，我尝试了一下，发现问题在我的电脑上已经修复了
![image](https://github.com/version-fox/vfox/assets/7099604/898e1d10-69ca-416c-9c80-fc2129e9e3ad)

我回想我的设置，可能时我在环境变量中设置了`JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8`导致的
![image](https://github.com/version-fox/vfox/assets/7099604/031bdce6-c33e-41eb-a7f5-d2e778b8939b)
但是我当时也重启过电脑，记得当时并没有生效
现在好像生效了

**Comment by greesBird** [comment]
在环境变量里加了JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8后，乱码问题就消失了
