### ISSUE TITLE
[Question] 下载文件时奇慢无比，但是在浏览器直接打开下载链接马上就下载好了

### ISSUE THREAD

**Issue by wyf195075595** [version-fox/vfox#306]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
vfox version 0.5.3

**OS**
Linux

**Question Description**
下载文件时奇慢无比

![image](https://github.com/version-fox/vfox/assets/60338824/266e832c-3faa-40bd-8208-7e9de0ef9a8f)
https://www.python.org/ftp/python/3.8.19/Python-3.8.19.tar.xz

但是在浏览器直接打开下载链接马上就下载好了

**Comment by bytemain** [comment]
应该是你的浏览器有代理吧？终端没有设置代理？

**Comment by wyf195075595** [comment]
> 应该是你的浏览器有代理吧？终端没有设置代理？

用了 clash 系统代理，默认应该都会用上吧

**Comment by yanecc** [comment]
> > 应该是你的浏览器有代理吧？终端没有设置代理？
> 
> 用了 clash 系统代理，默认应该都会用上吧

为vfox单独设置代理试一下

``` shell
vfox config proxy.enable true
vfox config proxy.url http(s)://proxy_host:proxy_port
```

**Comment by jan-bar** [comment]
我改了下插件脚本，可以试试看。

![image](https://github.com/version-fox/vfox/assets/14202095/4ea7e929-a01c-408a-bae7-bc587ae04d22)

**Comment by wyf195075595** [comment]
> > > 应该是你的浏览器有代理吧？终端没有设置代理？
> > 
> > 
> > 用了 clash 系统代理，默认应该都会用上吧
> 
> 为vfox单独设置代理试一下
> 
> ```shell
> vfox config proxy.enable true
> vfox config proxy.url http(s)://proxy_host:proxy_port
> ```

确实有用

**Comment by wyf195075595** [comment]
> 我改了下插件脚本，可以试试看。
> 
> ![image](https://private-user-images.githubusercontent.com/14202095/339224938-4ea7e929-a01c-408a-bae7-bc587ae04d22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjA4MDcsIm5iZiI6MTcxODI2MDUwNywicGF0aCI6Ii8xNDIwMjA5NS8zMzkyMjQ5MzgtNGVhN2U5MjktYTAxYy00MDhhLWJhZTctYmM1ODdhZTA0ZDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA2MzUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYWY5YjYzOTI1NDc2NjNkMTM0MGQ2ZjliNzhkZGZjMjcwYzkwNTY0MTFlZGMyOGI1OTYxZDQwOTY4MzQwODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nAH-ps-vPDKteakqDqx0q2d-W1dN2SU7MtFSl61TiJc)

网络没问题后，又出现了 git checkout 错误
![image](https://github.com/version-fox/vfox/assets/60338824/091090cd-fb38-495f-aa67-44cefee559dc)

在windows 是没问题的， 这个是ubuntu 上出了问题

**Comment by bytemain** [comment]
这个报错是磁盘没用空间了： No space left on device

**Comment by wyf195075595** [comment]
> 这个报错是磁盘没空间了： No space left on device

那我明白了，我这边问题。感谢大佬们解惑🤗
