### ISSUE TITLE
Support Self Update

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#31]
The current update method requires the use of third-party tools such as `homebrew` to upgrade or manually download the binary of the latest version for installation. We can support self-updating, which makes it easier to use, e.g. `vfox upgrade`

https://github.com/sanbornm/go-selfupdate

**Comment by ankit-pn** [comment]
hey i would love to work on this. it would be great if you assign this to me! Thanks

**Comment by aooohan** [comment]
@ankit-pn Hi, I'm glad to hear that you're interested in working on this. I've assigned the task to you. Thanks for your contribution!

**Comment by ankit-pn** [comment]
hey, there is no arm64 build for version 0.2.2. we should include a build for it also.

**Comment by aooohan** [comment]
We do provide a build for AArch64, which is equivalent to ARM64.

**Comment by aooohan** [comment]
Close in favor of #239
