### ISSUE TITLE
[BUG]: Bun installation error

### ISSUE THREAD

**Issue by Doodidan** [version-fox/vfox#315]
**Version**
0.5.3
**OS**
Windows

**Describe the bug**
```shell
vfox install bun@latest
plugin [PreInstall] method error: no version number provided
failed to install bun
```

Actually there is fix in ahai-code/vfox-bun#2 but it doesn't work for `latest` keyword. Also [vfox-bun repo](https://github.com/ahai-code/vfox-bun) seems to be not maintained for 2 months already so any attention will be appreciated.

**Comment by yanecc** [comment]
The version codes such as `latest` are not necessarily designed by the plugin author. Here is a temporary patch to enable the use of `latest`, add the following code before the loop in the PreInstall function of the bun plugin:

```
    table.sort(releases, function(a, b)
        return util:compare_versions(a, b)
    end)
    if ctx.version == "latest" then
        return releases[1]
    end
```

**Comment by ahai-code** [comment]
I have fixed this issue. Please upgrade the plugin to 0.1.2.
