### ISSUE TITLE
[BUG]: vfox安装的mvn不能找到同样用vfox安装的java的环境变量

### ISSUE THREAD

**Issue by mapleafly** [version-fox/vfox#316]
**Version**
0.51
**OS**
Windows11

**Describe the bug**
安装的mvn不能在powershell中执行。

执行mvn -version 报错如下：
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.

操作过程如下：
先删除了所有插件，修改sdkPath: D:\version-fox。 重装插件，重装sdk。
首先安装的是java，安装完java后，环境变量自动变更为：
JAVA_HOME: D:\version-fox\java\current
VERSION_FOX_PATH： D:\version-fox\java\current\bin
path ： D:\version-fox\java\current\bin

在cmd和powershell中执行java一切正常。

下一步安装maven，安装完成，执行 vfox use maven@3.8.6提示成功。 在powershell中执行 mvn -version 提示以上的报错。
查看环境变量，没有任何和mvn相关的环境变量生成。
.tool-versions文件中也没有生成mvn相关的内容。

求指教这是什么原因造成的。

另外，gradle也是这个问题，大概需要java支持的都有这个问题？ nodejs已经安装，没有出现问题。

**Comment by yanecc** [comment]
我没能复现，在powershell中似乎表现正常
```
PS C:\Users\Sunrise> mvn -v
Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: C:\Users\Sunrise\.version-fox\cache\maven\current
Java version: 21.0.2, vendor: Oracle Corporation, runtime: C:\Users\Sunrise\.version-fox\cache\java\current
Default locale: zh_CN, platform encoding: UTF-8
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```
可能需要检查一下`vfox use maven@3.8.6`之后`JAVA_HOME`环境变量的值

注意：需要确定vfox为最新版本`0.5.3`且不是通过scoop安装

**Comment by mapleafly** [comment]
> 我没能复现，在powershell中似乎表现正常
> 
> ```
> PS C:\Users\Sunrise> mvn -v
> Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
> Maven home: C:\Users\Sunrise\.version-fox\cache\maven\current
> Java version: 21.0.2, vendor: Oracle Corporation, runtime: C:\Users\Sunrise\.version-fox\cache\java\current
> Default locale: zh_CN, platform encoding: UTF-8
> OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
> ```
> 
> 可能需要检查一下`vfox use maven@3.8.6`之后`JAVA_HOME`环境变量的值
> 
> 注意：需要确定vfox为最新版本`0.5.4`且不是通过scoop安装

卸载老版本，重新安装了0.5.4。问题依旧。
      
请问正确的mvn  use成功后，会在环境变量那里自动设置什么呢？我这里是什么变化都没有。

在管理员模式下，执行vfox use maven@3.9.8  不退出窗口环境的情况下， 通过vfox list maven 可以看到当前指定的版本 （绿色 <— current标识），此时执行mvn -version是有效的。

但是重启powershell后，再执行vfox list maven  这个当前标识就不见了，执行mvn -version 会提示错误：
mvn : 无法将“mvn”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。

**Comment by yanecc** [comment]
> 请问正确的mvn use成功后，会在环境变量那里自动设置什么呢？

使用maven需要`JAVA_HOME`环境变量指向JDK安装路径或`PATH`中有java可执行程序。所以确保使用maven之前环境变量正确（运行`vfox use java`）。

> 执行vfox use maven@3.9.8 不退出窗口环境的情况下， 通过vfox list maven 可以看到当前指定的版本 （绿色 <— current标识），此时执行mvn -version是有效的。

`vfox use sdk`仅在当前shell生效，需要长期使用，使用：`vfox use -g sdk`
详细阅读：https://vfox.lhan.me/guides/quick-start.html#_5-switch-runtime
文档关于默认范围的描述过时了，当前Windows未指定作用域时默认范围也是当前session

**Comment by mapleafly** [comment]
> > 请问正确的mvn use成功后，会在环境变量那里自动设置什么呢？
> 
> 使用maven需要`JAVA_HOME`环境变量指向JDK安装路径或`PATH`中有java可执行程序。所以确保使用maven之前环境变量正确（运行`vfox use java`）。
> 
> > 执行vfox use maven@3.9.8 不退出窗口环境的情况下， 通过vfox list maven 可以看到当前指定的版本 （绿色 <— current标识），此时执行mvn -version是有效的。
> 
> `vfox use sdk`仅在当前shell生效，需要长期使用，使用：`vfox use -g sdk` 详细阅读：https://vfox.lhan.me/guides/quick-start.html#_5-switch-runtime 文档关于默认范围的描述过时了，当前Windows未指定作用域时默认范围也是当前session

非常感谢，加上 -g 就可以了。
