### ISSUE TITLE
Support environment variable settings to download mirror

### ISSUE THREAD

**Issue by lovelope** [version-fox/vfox#33]
**Version**
All
**OS**
macOS、Linux、Windows

**Describe the bug**
Like nvm, users can set the nodejs download mirror location.
```bash
NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/mirrors/node
```
Instead of adding additional plugins.
https://github.com/version-fox/vfox/issues/24

**Comment by yimiaoxiehou** [comment]
i hope can use vfox available to list mirror plugins .
it will implement this feature better.
![image](https://github.com/version-fox/vfox/assets/27064164/79dbf647-12df-44d5-afdd-d956c6972203)

**Comment by yimiaoxiehou** [comment]
> i hope can use `vfox available` to list mirror plugins . it will implement this feature better. ![image](https://private-user-images.githubusercontent.com/27064164/300363881-79dbf647-12df-44d5-afdd-d956c6972203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTQ4NTUsIm5iZiI6MTcwNjUxNDU1NSwicGF0aCI6Ii8yNzA2NDE2NC8zMDAzNjM4ODEtNzlkYmY2NDctMTJkZi00NGQ1LWFmZGQtZDk1NmM2OTcyMjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA3NDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZmExYThjYmNjMGZlMDgyYTEyMjI3NmM0Yzg5NjhlYWQ0MjRkMzUyYmNmZmVjMTY0ZmJlMThlOWY1MDRiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fPwZJooZJg7cKLHPoxpkZADALhLT1Fl3Rs8udZB4NoY)
> 
> `vfox available` can show flutter and flutter-cn now. maybe can add `vfox available -u` cmd to refresh list by [version-fox-plugins](https://github.com/version-fox/version-fox-plugins)

em，`vfox available` can auto refresh by [version-fox-plugins](https://github.com/version-fox/version-fox-plugins) not need any arg。 😄 
after my mirror plugin accept. it added in list.
![image](https://github.com/version-fox/vfox/assets/27064164/c32fdcb1-73a3-4834-9e99-554bfb7cda18)


@lovelope  now, you can use `vfox add nodejs/npmmirror  --alias nodejs` to use https://cdn.npmmirror.com(aliyun mirror) as node download source

![image](https://github.com/version-fox/vfox/assets/27064164/f4daeafa-ffe9-4c81-9bd6-f8f6a2269f74)

**Comment by lovelope** [comment]
LGTM

**Comment by aooohan** [comment]
Looking at it this way, the original option 2 is more reasonable. ;)
