### ISSUE TITLE
[Question] get checksum failed

### ISSUE THREAD

**Issue by pinggaimuier** [version-fox/vfox#330]
**OS**
Windows

**Question Description**
vfox install nodejs@21.15.1                                                                                        
plugin [PreInstall] method error: C:\Users\pinggai\.version-fox\plugin\nodejs\hooks\pre_install.lua:51: get checksum failed                                                                                                                     
stack traceback:                                                                                                        
        [G]: in function 'error'                                                                                        
        C:\Users\pinggai\.version-fox\plugin\nodejs\hooks\pre_install.lua:51: in main chunk                             
        [G]: ?                                                                                                          
failed to install nodejs

**Comment by ruhengChen** [comment]
发现这是由于设置的仓库地址错误
需要按下面这个配置才行
export VFOX_NODEJS_MIRROR=https://cdn.npmmirror.com/binaries/node

**Comment by aooohan** [comment]
Please refer to https://github.com/version-fox/vfox/issues/330#issuecomment-2304915718
