### ISSUE TITLE
[BUG]: fail to install clang@18.1.8

### ISSUE THREAD

**Issue by Dandjinh** [version-fox/vfox#332]
**Version**
```shell
NAME:
   vfox - vfox is a tool for runtime version management.

USAGE:
   vfox [command] [command options]

VERSION:
   0.5.4
```

**OS**
Debian 12

**Describe the bug**
```shell
Preinstalling clang@18.1.8...
Downloading... 100% [===================================================================================================================================================================================] (1.2 MB/s)
Verifying checksum ...
WARNING: Checksum is not provided, skip verify...
Unpacking /home/dandjinh/.version-fox/cache/clang/pixi-x86_64-unknown-linux-musl.tar.gz...
  × 'clang=18.1.8' is not a valid package name. Package names can only contain 0-9, a-z, A-Z, -, _, or .

Failed to execute command: /home/dandjinh/.version-fox/cache/clang/v-18.1.8/clang-18.1.8/pixi global install -qc conda-forge clang=18.1.8
```

**Comment by yanecc** [comment]
This is because the vfox-clang plugin uses pixi for installation, and it's an error from pixi, which should be fixed soon in the next version.
https://github.com/prefix-dev/pixi/issues/1685

**Comment by Dandjinh** [comment]
@yanecc thanks! BTW, is there any temporary solutions to get pass the problem or just wait for the next version of the clang plugin?

**Comment by yanecc** [comment]
The vfox-clang plugin is expected to resume working when the next pixi release is available, so it may not be updated. As for the temporary solution, of course, that is to use the working version of pixi. You can modify the lib/util.lua file in the vfox-clang plugin directory and change the following line

https://github.com/version-fox/vfox-clang/blob/0223d250fd59061ce9ec1752d69de40eea894191/lib/util.lua#L99

to: `file = releaseURL .. "download/v0.25.0/" .. file`. Then it can work now.

**Comment by Dandjinh** [comment]
`file = releaseURL .. "download/v0.25.0/" .. file` works fine, thanks a lot.
