### ISSUE TITLE
[BUG]: 安装node v22.6.0，不管是全局还是当前作用域都会提示不是内部或外部命令

### ISSUE THREAD

**Issue by Azir-11** [version-fox/vfox#339]
**Version**
vfox version 0.5.4
**OS**
Windows

**Describe the bug**
当切换node的版本至22的时候，会提示：
'node' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
其他版本不会
演示：
![image](https://github.com/user-attachments/assets/95f1034f-9306-48d0-8ec2-f81ddac42713)

补充：
1. 这台电脑是刚重装的系统，环境变量是纯净的，没有污染或者覆盖
2. 此前没有单独安装过node

这是我第一次使用这个软件，不清楚是否由于我个人问题引起的，如果是我个人犯蠢还望海涵😂，感谢您的时间

**Comment by jan-bar** [comment]
参照：[挂载vfox到你的Shell](https://vfox.lhan.me/zh-hans/guides/quick-start.html#_2-%E6%8C%82%E8%BD%BDvfox%E5%88%B0%E4%BD%A0%E7%9A%84shell)

window的cmd.exe只支持全局安装，功能比较少。

推荐使用[clink或cmderr](https://github.com/version-fox/vfox?tab=readme-ov-file#2-%EF%B8%8F-hook-vfox-into-your-shell-pick-one-that-works-for-your-shell-%EF%B8%8F)

**Comment by Azir-11** [comment]
好的，感谢
