### ISSUE TITLE
[Question] 无法安装 java8 ，尝试安装其他几个版本，只有 21 安装成功了，是什么安装哪个环节出问题了吗？

### ISSUE THREAD

**Issue by sujianjob** [version-fox/vfox#341]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
The version you are currently using

**OS**
=Linux

**Question Description**
无法安装 java8 ，尝试安装其他几个版本，只有 21 安装成功了

root@192-168-1-238:~# vfox search java
Please select a version of java to install [type to search]: 
   v22.0.1+8
   v21.0.2+13 (LTS)
   v20.0.2+9
   v19.0.2+7
   v18.0.2.1+1
   v17.0.2+8 (LTS)
   v16.0.2+7
   v15.0.2+7
   v14.0.2+12
   v13.0.2+8
   v12.0.2+10
   v11.0.16+8 (LTS)
   v10.0.2
   v9.0.4
->  v8.0.342+7 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Preinstalling java@8.0.342+7...
Downloading... 100% [=================================================================================================================================================================================================] (2.7 MB/s)         
failed to download java@8.0.342+7 file, err:unexpected EOF
root@192-168-1-238:~# vfox search java
Please select a version of java to install [type to search]: 
   v22.0.1+8
   v21.0.2+13 (LTS)
   v20.0.2+9
   v19.0.2+7
   v18.0.2.1+1
->  v17.0.2+8 (LTS)
   v16.0.2+7
   v15.0.2+7
   v14.0.2+12
   v13.0.2+8
   v12.0.2+10
   v11.0.16+8 (LTS)
   v10.0.2
   v9.0.4
   v8.0.342+7 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Preinstalling java@17.0.2+8...
Downloading... 100% [===============================================================================================================================================================================================] (2.4 MB/s)           
Verifying checksum ...
WARNING: Checksum is not provided, skip verify...
Unpacking /root/.version-fox/cache/java/openjdk-17.0.2_linux-x64_bin.tar.gz...
Install java@17.0.2+8 success! 
Please use vfox use java@17.0.2+8 to use it.
root@192-168-1-238:~# vfox search java
Please select a version of java to install [type to search]: 
   v22.0.1+8
   v21.0.2+13 (LTS)
   v20.0.2+9
   v19.0.2+7
   v18.0.2.1+1
   v17.0.2+8 (LTS)
   v16.0.2+7
   v15.0.2+7
   v14.0.2+12
   v13.0.2+8
   v12.0.2+10
   v11.0.16+8 (LTS)
   v10.0.2
   v9.0.4
->  v8.0.342+7 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Preinstalling java@8.0.342+7...
Downloading... 100% [===============================================================================================================================================================================================] (996 kB/s)           
failed to download java@8.0.342+7 file, err:unexpected EOF
root@192-168-1-238:~# vfox search java
Please select a version of java to install [type to search]: 
   v22.0.1+8
   v21.0.2+13 (LTS)
   v20.0.2+9
   v19.0.2+7
   v18.0.2.1+1
   v17.0.2+8 (LTS)
   v16.0.2+7
   v15.0.2+7
   v14.0.2+12
   v13.0.2+8
   v12.0.2+10
   v11.0.16+8 (LTS)
   v10.0.2
->  v9.0.4
   v8.0.342+7 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Preinstalling java@9.0.4...
Downloading... 100% [==================================================================================================================================================================================================] (1.8 MB/s)        
failed to download java@9.0.4 file, err:unexpected EOF
root@192-168-1-238:~# vfox search java
Please select a version of java to install [type to search]: 
   v22.0.1+8
   v21.0.2+13 (LTS)
   v20.0.2+9
   v19.0.2+7
   v18.0.2.1+1
   v17.0.2+8 (LTS)
   v16.0.2+7
   v15.0.2+7
   v14.0.2+12
   v13.0.2+8
   v12.0.2+10
->  v11.0.16+8 (LTS)
   v10.0.2
   v9.0.4
   v8.0.342+7 (LTS)
Press ↑/↓ to select and press ←/→ to page, and press Enter to confirm
Preinstalling java@11.0.16+8...
Downloading... 100% [=================================================================================================================================================================================================] (2.8 MB/s)         
failed to download java@11.0.16+8 file, err:unexpected EOF

**Comment by ieayoio** [comment]
看着应该是网络问题

**Comment by aooohan** [comment]
> failed to download java@11.0.16+8 file, err:unexpected EOF

网络问题。用的都是官网数据源，有时候确实不友好。

**Comment by aooohan** [comment]
可以配置一下代理试试：https://vfox.lhan.me/zh-hans/guides/configuration.html#%E4%BB%A3%E7%90%86%E8%AE%BE%E7%BD%AE
