### ISSUE TITLE
 Switch node version not working 

### ISSUE THREAD

**Issue by baymax55** [version-fox/vfox#35]
**Version**
VersionFox version 0.2.2
**OS**
Windows 11 Pro for Workstations Insider Preview 64-bit (10.0,Build 26040)

**Describe the bug**
 Switch node version not working 

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/35788491/6d824c60-e46f-464d-b1a0-7c8fcdade802)

**Comment by aooohan** [comment]
What `nodejs` plugin version are you using? You can use `vfox info node` command to look at plugin version.

In addition, according to the prompt, you have not configured the hook correctly, please refer to the following steps to configure the hook:
```powershell
# For PowerShell, add the following line to your $PROFILE:
Invoke-Expression "$(vfox activate pwsh)"
```

**Comment by baymax55** [comment]
Same for java
![image](https://github.com/version-fox/vfox/assets/35788491/e3ed6f0e-19bd-4cfa-b909-c4fa53e89ad9)

**Comment by baymax55** [comment]
Adding `Invoke-Expression "$(vfox activate pwsh)"` in the configuration file is work for me.

Thanks.

> 您所报告的问题上确实存在一个bug，即：在windows环境下，cmd与powershell应当能够在未经任何配置的情况下即可开箱使用。但为了更好的使用体验, 对于powershell有正确的配置方案：
> 
> 1. 在powershell中使用$PROFILE命令确认配置文件路径。若该文件不存在，则可能需要您手动新建一个；
> 2. 在上一步寻得的文件中，增加一行配置：
>    ` Invoke-Expression "$(vfox activate pwsh)"`
> 3. 重新打开powershell。由于windows的默认策略，在上述动作完成后，也许您会看到关于powershell的配置脚本被禁用的提示。如果您见到了该提示，那么请参考：[about_execution_policies](https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4#long-description)来解决该问题。
>    一般来说您可以通过执行`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`来允许配置脚本可运行。
>    在完成上述操作后，即可重新打开powershell使用vfox！
> 
> > btw, `vfox`默认session作用域
> 
> Indeed, the issue you've reported is a bug: in a Windows environment, both cmd and PowerShell should be ready to use out of the box without any configuration. However, to enhance the user experience, we have a proper configuration procedure for PowerShell:
> 
> 1. In PowerShell, use the `$PROFILE` command to confirm the path of the configuration file. If this file does not exist, you may need to manually create one.
> 2. In the file found in the first step, add the following configuration line: `Invoke-Expression "$(vfox activate pwsh)"`.
> 3. Reopen PowerShell. Due to Windows' default policy, after completing the above steps, you might see a prompt indicating that the PowerShell configuration script has been disabled. If you encounter this prompt, you can refer to [about_execution_policies](https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.4#long-description) to resolve this issue. Typically, you can allow the configuration script to run by executing `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`.
> 4. After completing the above steps, you can reopen PowerShell and use vfox!
> 
> Please note, by default, the scope of `vfox` is set to session.

**Comment by baymax55** [comment]
Sorry, I'm confused, it seems only work for Java is ok, but not for Node and Golang 

![image](https://github.com/version-fox/vfox/assets/35788491/c5cf5bfd-d5ea-42d6-9a12-53467d622738)

**Comment by aooohan** [comment]
@baymax55 Can you post your snapshot of `$PROFILE` configuration?


<img width="1150" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/8a47c03d-a4fe-433d-aeeb-48d12196775f">

**Comment by baymax55** [comment]
> @baymax55 Can you post your screenshot of `$PROFILE` configuration content?
> 
> <img alt="image" width="1150" src="https://private-user-images.githubusercontent.com/40265686/300710033-8a47c03d-a4fe-433d-aeeb-48d12196775f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTg3NjAsIm5iZiI6MTcwNjU5ODQ2MCwicGF0aCI6Ii80MDI2NTY4Ni8zMDA3MTAwMzMtOGE0N2MwM2QtYTRmZS00MzNkLWFlZWItNDhkMTIxOTY3NzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA3MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMmIzYmJmNzhiYzk5MThmOGQwZGVmMTA0YzU3NGJmMjM5ZDNiNWI0OTkyZjhjODAyY2Q3N2MzMWY3MjlmYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uFpaTVytfqvFamtpeZxpURzfTqmQSt6jjBKZLDdaaBg">

![image](https://github.com/version-fox/vfox/assets/35788491/23665e0c-b46a-4c9f-a05a-5a07ec86f76d)

**Comment by aooohan** [comment]
@baymax55 
Everything looks fine.  

You installed Node16.20.1 and Golang 1.19.4 separately, not through `vfox`, right?
If so, you need to uninstall it first as `vfox` will configure the user variables for you, if you configure the system variables manually, windows will prioritize the PATH in the system variables.

**Comment by baymax55** [comment]
> @baymax55 Everything looks fine.
> 
> You installed Node16.20.1 and Golang 1.19.4 separately, not through `vfox`, right? If so, you need to uninstall it first as `vfox` will configure the user variables for you, if you configure the system variables manually, windows will prioritize the PATH in the system variables.

Yes, I installed Node16.20.1 and Golang 1.19.4 separately.

I will try to reinstall it

**Comment by baymax55** [comment]
Reinstall it still can not switch Node and Golang version

**Comment by aooohan** [comment]
Alright, please post your `$PATH` content by `$env:path` command. Note that you need to reopen `Powershell`

**Comment by aooohan** [comment]
As I said above, you need to **delete the PATH you configured yourself**. The path priority you configured yourself is higher than that of **vfox**, so it seems that **vfox** has never taken effect.
<img width="867" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/e50ea1c3-23b9-44c9-80eb-408d6474bea1">

**Comment by baymax55** [comment]
> As I said above, you need to **delete the PATH you configured yourself**. The path priority you configured yourself is higher than that of **vfox**, so it seems that **vfox** has never taken effect. <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/40265686/300725117-e50ea1c3-23b9-44c9-80eb-408d6474bea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDMwMjMsIm5iZiI6MTcwNjYwMjcyMywicGF0aCI6Ii80MDI2NTY4Ni8zMDA3MjUxMTctZTUwZWExYzMtMjNiOS00NGM5LTgwZWItNDA4ZDY0NzRiZWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA4MTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZDkwN2U1NGM0ZmRmYzBjNGM5MjQ4ZWFkM2I5N2NiOGM1MzM5ZjFlMGEwMGIwNzk1MTlkMjQyZjUxZWQyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aThzLZccUSbTd7Ft5EaI5BQsMjDAaJAqMlMud0h_StM">

I just deleted the environment variables of node and golang, but it still doesn't work. As you said, the environment variable priority of java 17 is also higher than that of vfox, why does it work?
@aooohan 
![image](https://github.com/version-fox/vfox/assets/35788491/73c587f5-a78c-4764-b629-ac3ae92194ff)

**Comment by aooohan** [comment]
There's no good way to do this, only check the **PATH** from the user variable and the system variable. Find it and remove.

![image](https://github.com/version-fox/vfox/assets/40265686/01107eb9-5621-4b40-ab9a-cd83a782c01a)

**Comment by aooohan** [comment]
Since this has nothing to do with **vfox**, I will close this issue, wish you good luck.

**Comment by baymax55** [comment]
in addition:
I didn't do anything. I just installed nvm and took over the node version downloaded by vfox. I can switch the node version normally using nvm.

![image](https://github.com/version-fox/vfox/assets/35788491/d9bebb03-3776-4b69-b772-9a71f3d11865)

**Comment by aooohan** [comment]
@baymax55 https://discord.gg/JAuHXJ2b  Come in and talk.
