### ISSUE TITLE
[Question] Is it possible to create a release with the current version ?

### ISSUE THREAD

**Issue by ciscoski** [version-fox/vfox#354]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
0.5.4

**OS**
macOS、Linux、Windows

**Question Description**
Would it be possible to create a release for the current main ?
I've a couple of plugin that I would like to share but I can not because they depend from one of my last commit.

Thanks
Cisco

**Comment by bytemain** [comment]
Hello, 0.5.5 has released.

https://github.com/version-fox/vfox/releases/tag/v0.5.5
