### ISSUE TITLE
能否配置在自定义缓存路径 

### ISSUE THREAD

**Issue by Super1Windcloud** [version-fox/vfox#355]
<-- Please answer these questions before submitting them. Thank you. -->

**Version**
The version you are currently using

**OS**
macOS、Linux、Windows

**Question Description**
A clear and concise description of what the question is.

**Comment by baltarifcan** [comment]
我不是中文使用者，但这可能是你要找的：https://vfox.lhan.me/zh-hans/guides/configuration.html#%E5%AD%98%E5%82%A8%E8%B7%AF%E5%BE%84
