### ISSUE TITLE
Missing environment variable __VFOX_PID when using fish

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox#364]
I just got this one more time

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/5c31adcd-0f1e-4800-9e66-a8b6c95004e6">

switching to existing tmux panes (shell sessions) did not change anything. but creating a new pane helped. and node in `/Users/vv/.version-fox/temp/1727128800-4412/` folder has been resurrected

<img width="776" alt="image" src="https://github.com/user-attachments/assets/d7e955d4-3962-457f-b229-ec9aaa88167d">

ps: can a suspend process influence this somehow?

_Originally posted by @ZuBB in https://github.com/version-fox/vfox/issues/283#issuecomment-2392929009_

**Comment by jan-bar** [comment]
I don't usually use fish. I use the following go code and shell command to test that the go code cannot read the environment variable `__VFOX_PID`

![image](https://github.com/user-attachments/assets/315382ac-6ec0-468a-810d-ebd5141def85)

Affected Code: https://github.com/version-fox/vfox/blob/be6910b82c7aa04dbc632854f733883fdb7d3983/internal/shell/fish.go#L35

I use `set -x __VFOX_PID %self;` and the go code can successfully read the environment variable

![image](https://github.com/user-attachments/assets/32f20372-ab40-4861-8b80-25acc4c1c579)

@ZuBB  Could you test your problem using the modified code?

**Comment by ZuBB** [comment]
@jan-bar JFYI I will try to take a look at this on Wed

**Comment by jan-bar** [comment]
https://github.com/version-fox/vfox/blob/be6910b82c7aa04dbc632854f733883fdb7d3983/internal/env/flag.go#L17-L39

Because the current terminal does not have a "__VFOX_PID" environment variable, vfox will fall back to using `os.Getppid()`. Since all your terminals have the same parent process, all your terminals actually use the same temporary directory environment.

**Comment by ZuBB** [comment]
This explains why the existing tab started to work again after creating a new one. But it does not explain why the existing tab stopped working

**Comment by jan-bar** [comment]
https://github.com/version-fox/vfox/blob/be6910b82c7aa04dbc632854f733883fdb7d3983/internal/shell/fish.go#L59-L62

You may have closed a terminal over the past day, triggering a cleanup task. Since all your terminals share the temporary directory, the terminal that was not closed the previous day will be unavailable. At this time, when you open a new terminal, a new temporary directory will be created, and all other terminals will immediately reuse the environment.

**Comment by ZuBB** [comment]
That makes some sense. Thank you for your time

**Comment by ZuBB** [comment]
I have got one more issue, that might be related to this.

STR
* Open the new tmux tab;
* Set Node.js runtime to something else except default in this shell (`-s`);
* Do some Node.js stuff `(node -v)`;
* Create a new tmux tab;
* Do some Node.js stuff `(node -v)`. the default version of the runtime should be used;
* Move back to the "new" tab;
* Check node version. the version we used to set "disappear", the default one is used 😞

**Comment by jan-bar** [comment]
@ZuBB use `go install github.com/version-fox/vfox@ca4d9e6` Installed version test
Is the `__VFOX_PID` environment variable still missing?

**Comment by ZuBB** [comment]
no, its there

<img width="789" alt="image" src="https://github.com/user-attachments/assets/001e8e7b-89a5-4ef3-9060-f994165ba518">

**Comment by ZuBB** [comment]
a bit better screen that may give you some additional hints

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/82ffb02c-504f-4603-9859-5f95dcb7568c">

**Comment by ZuBB** [comment]
Hey, @jan-bar, can we have a new minor release with this fix? In my latest project (I ought to run it under WSL), I am getting this every 2 days

**Comment by ZuBB** [comment]
@jan-bar I am sorry to bother you again on this one, but it seems like even your fix (v0.6.1-pre is a build I got by you [advice](https://github.com/version-fox/vfox/pull/368#issuecomment-2556453736)) does not work

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/ed8476b5-0f46-45a0-911e-93c7984995cd" />

**Comment by jan-bar** [comment]
There must be something wrong with your configuration. The last number in the temporary directory is not the value of the `__VFOX_PID` environment variable.
![20250102_085139](https://github.com/user-attachments/assets/4895f7e0-3b50-452c-8e71-b9946babe873)

Below is the latest code I compiled manually, as well as the configuration of tmux and fish
![20250102_091846](https://github.com/user-attachments/assets/75eca392-d3fb-4be3-b322-78630767898e)

Then execute tmux to start two terminals. As shown in the figure, each terminal has its own correct environment variables.
![20250102_092218](https://github.com/user-attachments/assets/ba943ab1-dae2-4dcd-89ff-fe88e2b87566)

**Comment by ZuBB** [comment]
@jan-bar I am trying to find out what is wrong here. I hope you agree that two options are possible (or at least 2)
* there is some issue with either the configuration or with another software (fish shell, tmux, kitty?) at my side;
* still, there is some issue with vfox.

The case you describe is perfectly valid, but it is very basic. I am pretty sure I can replicate it on my laptop.

My workflow is slightly more complicated. I am working on a couple of projects at the same time. "working" here means that I open a new kitty window for each project. If a project requires a few shells, I start tmux within that kitty window/instance of fish shell and create as many tabs (full-size panes) as I need. When I need to switch to another project, I do "detach" in terms of tmux and close kitty's window and start over (either new kitty+new tmux or new kitty + tmux attach). In these cases, fish shells may live quite a long life.

Now, we need to think about which reason could lead to a situation when `PID` and `CURTMPPATH` may use different IDs. How can we exclude any of the options I mentioned at the start?

PS: after we discovered #375, I have only one version of node installed by `vfox`. 

BTW, as far as I remember, when this happens, `vfox` loses track of which version of the node is currently active. I will try to get a proof of that next time it happens

**Comment by ZuBB** [comment]
Can I set up some hook at my side to catch a moment when `ID` in `PID` and `CURTMPPATH` starts to differ? if so any advice on that? maybe it will help me understand what my action leads to that

**Comment by jan-bar** [comment]
@ZuBB I don't have such a complicated environment. I suggest you remove some programs for testing. For example, remove fish and use bash instead, remove tmux and use fish directly. I usually only use the bash that comes with the system, so I don't encounter such a complicated problem as yours.
