### ISSUE TITLE
[BUG]: 在webstorm中运行npm脚本时，vfox没有自动切换版本

### ISSUE THREAD

**Issue by thornboo** [version-fox/vfox#366]
**Version**
vfox version 0.5.4
**OS**
Windows

**Describe the bug**
我正在启动一个node18版本的项目，并且我全局设置的node版本是16，此时我已经通过vfox use -p nodejs@18设置了项目的node版本。但是当我运行npm脚本的时候，提示报错node版本为16，vfox并没有切换为node18版本，这个是什么原因呢？

**Screenshots[optional]**

<img width="952" alt="image_6" src="https://github.com/user-attachments/assets/4cce5b70-2bbd-499c-927e-d7a44f8a4278">

**Comment by Chance-fyi** [comment]
自动切换版本是命令行中的功能，IDE 中可以通过 `Settings > Languages & Frameworks > Node.js` 设置版本
