### ISSUE TITLE
Support Python plugin 

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#40]

**Comment by baymax55** [comment]
This seems to be the download link for python
`https://www.python.org/ftp/python/`

**Comment by aooohan** [comment]
> This seems to be the download link for python `https://www.python.org/ftp/python/`

Yes, you are right, thanks for the reminder.

**Comment by aooohan** [comment]
I've finished this Python plugin, and so far everything works fine under macOS. If anyone is interested, you can help me test it on Windows. Note: You need to manually compile the latest `vfox` build of master, in order to load and use this plugin. 😄

**Comment by baymax55** [comment]
> I've finished this Python plugin, and so far everything works fine under macOS. If anyone is interested, you can help me test it on Windows. Note: You need to manually compile the latest `vfox` build of master, in order to load and use this plugin. 😄

It seems that there is no document on how to build `vfox` in Windows. Can you provide a snapshot version?

I referred to this file `.gthub/workflows/compile-inno-setup.yml`, but I couldn’t understand it.

**Comment by aooohan** [comment]
> It seems that there is no document on how to build `vfox` in Windows. Can you provide a snapshot version?

Ok, i will do this later.😉

**Comment by baymax55** [comment]
> I've finished this Python plugin, and so far everything works fine under macOS. If anyone is interested, you can help me test it on Windows. Note: You need to manually compile the latest `vfox` build of master, in order to load and use this plugin. 😄

I used the latest `vfox` and Python plugin and reported the following error:
`WARNING: Checksum is not provided, skip verify...`
`failed to move file, err:rename C:\Users\Dell\.version-fox\cache\python\python-3.12.1-amd64.exe C:\Users\Dell\.version-fox\cache\python\v-3.12.1\python-3.12.1: The system cannot find the path specified.`

![image](https://github.com/version-fox/vfox/assets/35788491/d11d2156-4140-4b50-8d04-a4ceeff99286)

**Comment by aooohan** [comment]
> failed to move file, err:rename C:\Users\Dell\.version-fox\cache\python\python-3.12.1-amd64.exe C:\Users\Dell\.version-fox\cache\python\v-3.12.1\python-3.12.1: The system cannot find the path specified.

I have fixed this bug. 576ada7950d5b50007a414d0a3fbf9602df6204c,  Thanks! ; )
