### ISSUE TITLE
it not work for use command

### ISSUE THREAD

**Issue by snaigle** [version-fox/vfox#43]
**Version**
vfox 0.2.2
**OS**
macOS 14.2.1
zsh

**Describe the bug**
first
``` vfox use golang@1.21.1 ```
then
```  golang version ```
golang is still go1.18.6

**Screenshots[optional]**
<img width="1145" alt="image" src="https://github.com/version-fox/vfox/assets/491190/3d581785-ee03-4bfb-9dbd-35880a0f8602">

**Comment by aooohan** [comment]
Duplicate #35 

Please join discord: https://discord.com/invite/PdEvGXHp
