### ISSUE TITLE
Suggestion support for specific version manager files

### ISSUE THREAD

**Issue by pwall2222** [version-fox/vfox#47]
I have looked around in the docs but I have not found any mentions of this, but it would be a nice to add support for `version managers` files
Examples:
- `.nvmrc` [docs](https://github.com/nvm-sh/nvm?tab=readme-ov-file#nvmrc) | [code](https://github.com/nvm-sh/nvm/blob/4e2a71ba9be7ce628f4127c4306820f9eccac6fc/nvm.sh#L471)
- `.python-version`

**Comment by aooohan** [comment]
`vfox` has its own version management file, `.tool-versions`. It is the same as and compatible with `asdf`.

**Comment by aooohan** [comment]
`vfox` will create a `.tool-versions` file to record SDK version you use when use `vfox use -p <sdk-name>` command.

**Comment by pwall2222** [comment]
I did read that on the docs!
I just meant it would be a cool opt-in feature, as per the projects that use those files would remain "less" compatible with vfox

**Comment by aooohan** [comment]
> I did read that on the docs! I just meant it would be a cool opt-in feature, as per the projects that use those files would remain "less" compatible with vfox

Ok, I get what you meant now. To accomplish this, we need to add a new hook for the plugin, which is called when using the `vfox use `command.

**Comment by pwall2222** [comment]
That would be brilliant!

**Comment by ZuBB** [comment]
> > I did read that on the docs! I just meant it would be a cool opt-in feature, as per the projects that use those files would remain "less" compatible with vfox
> 
> Ok, I get what you meant now. To accomplish this, we need to add a new hook for the plugin, which is called when using the `vfox use `command.

This would be great! Can we expect that `.node-version` also will be supported?

PS: I just discovered this package, and I am already in love with it!

**Comment by aooohan** [comment]
> > > I did read that on the docs! I just meant it would be a cool opt-in feature, as per the projects that use those files would remain "less" compatible with vfox
> > 
> > 
> > Ok, I get what you meant now. To accomplish this, we need to add a new hook for the plugin, which is called when using the `vfox use `command.
> 
> This would be great! Can we expect that `.node-version` also will be supported?

If `.nvmrc `is OK, then `.node-version` is totally OK! But it's just a work in progress.

> 
> PS: I just discovered this package, and I am already in love with it!

Thanks!
