### ISSUE TITLE
what diff with set sdk with session or global

### ISSUE THREAD

**Issue by yimiaoxiehou** [version-fox/vfox#50]
by test，`vofx use`  `-g` or `-p` both create a new bash process and add sdk path on `PATH`，i don't know what diff with them?

**Comment by aooohan** [comment]
@yimiaoxiehou Please join Discord https://discord.gg/85c8ptYgb7 ;)

**Comment by aooohan** [comment]
I told u before https://github.com/version-fox/version-fox-plugins/pull/11#issuecomment-1925684486, because of you did not configure the shell hook correctly. ;)
