### ISSUE TITLE
Translation package repos hit 404

### ISSUE THREAD

**Issue by blackfyre** [version-fox/vfox#52]
**Version**
0.2.3
**OS**
Ubuntu (WSL2)

**Describe the bug**
When updating `apt` repos, vfox Translations hit 404

**Screenshots[optional]**
![image](https://github.com/version-fox/vfox/assets/1991410/fec5ad29-4825-4e3c-abaf-d94961468fcf)

**Comment by aooohan** [comment]
Hmm, this doesn't seem to be a problem I can solve. It should be a problem with `fury.io.`

**Comment by aooohan** [comment]
It seems a bit similar to https://github.com/meilisearch/meilisearch/discussions/2526

**Comment by transtone** [comment]
> Hmm, this doesn't seem to be a problem I can solve. It should be a problem with `fury.io.`

除了 fury.io ，还有哪个地址可以用的？文档里只有这一个地址，又说不归你管，那怎么处理呢？
