### ISSUE TITLE
[Feature Request] Add `Use` hooks for Plugins

### ISSUE THREAD

**Issue by bytemain** [version-fox/vfox#56]
as we discussed in <https://github.com/version-fox/version-fox-plugins/issues/14>

if we want to use `vfox use nodejs@20`, we want the plugin provide the local installed version that match 20.

for example:

```lua
function PLUGIN:PreUse(ctx) 
  local query = ctx.query
  local installed = ctx.installed
end
```

**Comment by aooohan** [comment]
This hook is also needed to solve the following issue:
- #47 
- #48

**Comment by bytemain** [comment]
Can you assign this to me? I can implement all the basic function and we can discuss what should be pass to the `PreUse` hooks and what it should return

**Comment by aooohan** [comment]
> Can you assign this to me? I can implement all the basic function and we can discuss what should be pass to the `PreUse` hooks and what it should return

Yes, why not.  But it's not just a matter of implementing a `PreUse` hook, I have to think about the relationship between ` vfox use` and `vfox env`.
`vfox use` just writes version info to `.tool-versions`, `vfox env` is where it really takes effect.
