### ISSUE TITLE
Re-install failure after incomplete installation

### ISSUE THREAD

**Issue by ghosind** [version-fox/vfox#63]
**Version**

0.2.3

**OS**

macOS

**Describe the bug**

If I terminate the install command during downloading and try to install again, vfox will print it is already installed.

For example:

```sh
$ vfox install zig@0.11.0
Preinstall zig@0.11.0...
Downloading... 11% [=====> 
^C
$ vfox install zig@0.11.0
zig@0.11.0 is already installed
```

**Comment by aooohan** [comment]
It may be caused by not cleaning up the folder in time. There is no handling of interruptions, just defer to clean up when failed. It seems to have little effect.
