### ISSUE TITLE
[BUG]: Duplicate path in vscode terminal, but normal in system terminal.

### ISSUE THREAD

**Issue by wmszhe** [version-fox/vfox#74]
**Version**
0.2.4
**OS**
macOS

**Describe the bug**
vscode terminal 中 path 重复，系统终端中正常

**Screenshots[optional]**
<img width="1002" alt="image" src="https://github.com/version-fox/vfox/assets/13552154/c7af7af7-1617-4f0d-a264-9baa432cb7e5">
<img width="962" alt="image" src="https://github.com/version-fox/vfox/assets/13552154/b75f761c-c4e5-491d-9232-5befb19f1ae7">

**Comment by wmszhe** [comment]
是否已经更新？0.2.6 依然存在这个问题

**Comment by aooohan** [comment]
> 是否已经更新？0.2.6 依然存在这个问题

服了, 修改了一半提交了😂

**Comment by aooohan** [comment]
https://github.com/version-fox/vfox/commit/8777ec7c0e91b2a94cbf0890a40c913b8759f908
