### ISSUE TITLE
java/azul-jdk 插件问题

### ISSUE THREAD

**Issue by daihy8759** [version-fox/vfox#81]
**Version**
The version you are currently using
**OS**
macOS

**Describe the bug**
JAVA_HOME路径不对导致切换不成功

**Screenshots[optional]**
![CleanShot 2024-03-06 at 10 47 31](https://github.com/version-fox/vfox/assets/6057326/e8b808c0-53d4-4c8e-9ab4-1c7649add8d5)

实际路径是

![CleanShot 2024-03-06 at 10 49 04](https://github.com/version-fox/vfox/assets/6057326/04fb1589-0128-457b-bfe6-9e1c94e9142e)

**Comment by aooohan** [comment]
This is fixed. You can update with the `vfox update java` command.

**Comment by daihy8759** [comment]
试过了还是不行

**Comment by aooohan** [comment]
<img width="891" alt="image" src="https://github.com/version-fox/vfox/assets/40265686/5a76836b-cfc9-4c14-b808-4ebc02012f0e">
没问题, 你插件卸载重新试试.

PATH重复这个问题, 0.2.4解决了大部分, 0.2.5全部解决.

**Comment by daihy8759** [comment]
卸载插件重新安装可以了，用vfox update java，重新安装jdk不行
