### ISSUE TITLE
Feature: Add a soft link to current version of sdk

### ISSUE THREAD

**Issue by sp0cket** [version-fox/vfox#84]
We can get the current version through a fixed directory, which can be used in the IDE configuration
Example:
```
~/.version-fox/cache/go/current -> ~/.version-fox/cache/go/v-1.22.1/golang-1.22.1
```

**Comment by bytemain** [comment]
nice idea.
@aooohan if we implements this feature, we can just put a `~/.version-fox/cache/go/current` to the path.

**Comment by aooohan** [comment]
> nice idea. @aooohan if we implement this feature, we can just put the `~/.version-fox/cache/go/current` to the `PATH` env.

The feature op is talking about can be done, it's for IDEA configuration, no problem.

BUT we can no longer put this path in the `PATH`, this is also the biggest difference between `vfox` and `asdf`, as we cannot implement `Session` scope by soft link solution, which only implement `Global` and `Project`.
