### ISSUE TITLE
How to show all available version ?

### ISSUE THREAD

**Issue by lakako** [version-fox/vfox#86]
**Version**
The version you are currently using
**OS**
Windows 11

**Describe the bug**
type 'vfox list java'

it just show 

```
no available version
```

**Comment by axdank** [comment]
@lakako you add the `java` plugin ?

steps: 
add vfox [hook](https://vfox.lhan.me/guides/quick-start.html#_2-hook-vfox-to-your-shell) to you shell

1. `vfox available` -> to list all available plugins
2. `vfox add java/adoptium-jdk` -> example for add adoptium-jdk from the list
3. `vfox install java@21` or `vfox search java` -> example for install a version of java from adoptium-jdk
4. `vfox use java` -> set version to use
5. `vfox ls` or `vfox list java` -> obtain the installed versions or specifically the installed java versions

**Comment by aooohan** [comment]
`Available` command:
https://vfox.lhan.me/usage/core-commands.html#available
`List` command:
https://vfox.lhan.me/usage/all-commands.html#list

**Comment by transtone** [comment]
https://github.com/version-fox/vfox/issues/333
