### ISSUE TITLE
[Feature]: Only enter the major version number to switch versions

### ISSUE THREAD

**Issue by lovelope** [version-fox/vfox#87]
#### 1. Your usage scenarios?
Currently, installing and switching SDK versions requires entering the exact version number, which increases my mental burden. In fact, I only need large version numbers to be compatible for it to work properly. I hope I can install and switch SDK versions by entering a major version number like nvm.
#### 2. What is your expected outcome?
Enter the major version number of the large SDK to install and switch the SDK version

**Comment by bytemain** [comment]
which sdk are you using?

the feature is currently supported while installing nodejs sdk, also will support `use` command in next version fox version.

**Comment by lovelope** [comment]
My environment requires nodejs SDK. After I upgraded to version 0.0.2, I can install the corresponding version, but I cannot switch versions.

**Comment by bytemain** [comment]
yes, the switch feature will be available on the next version:

![CleanShot 2024-03-08 at 13 57 11@2x](https://github.com/version-fox/vfox/assets/13938334/f5bec415-159a-41dc-a322-7b56d68f688c)

**Comment by joaohenrifranco** [comment]
Supporting entering only the minor version would also be useful for the python plugin eg. `vfox install python@3.10`

**Comment by bytemain** [comment]
> Supporting entering only the minor version would also be useful for the python plugin eg. `vfox install python@3.10`

can be done after we implemented this: 
- https://github.com/version-fox/vfox/discussions/92

we can share some code between plugins that make them all have this feature
