### ISSUE TITLE
[Feature]: Support scoop installation

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox#90]
#### 1. Your usage scenarios?
Support for Windows users can install `vfox` via `scoop`
#### 2. What is your expected outcome?
Support for Windows users can install `vfox` via `scoop`

**Comment by do9core** [comment]
I have created one, you can check it [here](https://gist.githubusercontent.com/do9core/2729f8721850ca6af6b9ee6504a2adb7/raw/2ae9ee89f220485e4fe10e3864d54280ae24c451/vfox.json)

But this script just install it on the machine, doesn't setup the PowerShell profile.

**Comment by aooohan** [comment]
> I have created one, you can check it [here](https://gist.githubusercontent.com/do9core/2729f8721850ca6af6b9ee6504a2adb7/raw/2ae9ee89f220485e4fe10e3864d54280ae24c451/vfox.json)

I have push `vfox` to the Main bucket which based on your script, thanks!
