### ISSUE TITLE
[BUG]: 不支持Windows系统上的GitBash

### ISSUE THREAD

**Issue by SnobbyVirus1973** [version-fox/vfox#93]
**Version**
VersionFox version 0.2.4
**OS**
Windows 11 23H2 22631.3235

**Describe the bug**
在Windows系统上使用安装包安装了vfox，并且配置了bash和powershell两个
在GitBash和PowerShell使用vfox相关命令都正常，但是如果使用`vfox use`命令设置sdk后，GitBash所有的命令都不能用了包括`ls`命令，但是PowerShell正常，使用SDK命令发现SDK也是正常切换版本的。

如果我使用`vfox use -p`在某个项目目录下设置sdk后，在其他目录下使用GitBash一切正常，但是`cd`到项目目录后，GitBash命令又都不能用了

如果我使用`vfox use -g`在全局下设置sdk后，全系统下GitBash命令都不能用

**Screenshots[optional]**
GitBash在切换到项目目录下不能用了，但是PowerShell还好用
![image](https://github.com/version-fox/vfox/assets/33438668/736722b8-02d3-4ee3-99aa-c3fabe3ff3f7)

~/.bashrc文件内容
![image](https://github.com/version-fox/vfox/assets/33438668/232f2a3b-9654-442b-a91b-08d0faee7a64)

**Comment by aooohan** [comment]
PATH分隔符的问题，下个版本修复。

**Comment by aooohan** [comment]
NOTE: #98
