### ISSUE TITLE
[BUG]: Dotnet无法正常使用

### ISSUE THREAD

**Issue by Gaven-F** [version-fox/vfox#94]
**Version**
vfox 版本：0.2.4
.net 版本：8.0.2
**OS**
Windows

**Describe the bug**
无法正常使用dotnet

**Screenshots[optional]**
<img width="562" alt="1709903471381" src="https://github.com/version-fox/vfox/assets/133743603/0f3a01d5-35bd-4945-ae17-ddf1b525bb3d">

**Error Message**
Error: [C:\Users\GF\.version-fox\cache\dotnet\v-8.0.2\dotnet-8.0.2\host\fxr] does not exist

**个人猜想**
感觉就是路径错误，正常情况下是没有那个host文件夹的在Windows系统上

**Comment by Gaven-F** [comment]
经过测试发现，好多在arm上支持都不怎么良好，如通过vfox安装了nodejs后，无法运行对next进行测试开发和打包（即：无法正常下载next的编译器）

**Comment by Gaven-F** [comment]
且额外安装了nodejs后，vfox无法正常检测到nodejs的存在
这里感觉可以参考nvm的管理逻辑

**Comment by aooohan** [comment]
> 且额外安装了nodejs后，vfox无法正常检测到nodejs的存在
> 这里感觉可以参考nvm的管理逻辑

目前确实没有这个功能，需要放到插件里去实现。

**Comment by aooohan** [comment]
> 经过测试发现，好多在arm上支持都不怎么良好，如通过vfox安装了nodejs后，无法运行对next进行测试开发和打包（即：无法正常下载next的编译器）

通过手动安装node arm上可以运行next吗？

vfox本质上就是分发二进制和配置环境变量。

**Comment by Gaven-F** [comment]
> 通过手动安装node arm上可以运行next吗？
> 
> vfox本质上就是分发二进制和配置环境变量。

直接安装或者使用nvm都是正常的，我也很疑惑是那个环节出问题了
