### ISSUE TITLE
[Question] windows上如何挂载？

### ISSUE THREAD

**Issue by 0000005** [version-fox/vfox#95]
![image](https://github.com/version-fox/vfox/assets/9690089/b0ba7dc1-9098-4fa5-88fd-f98973693ee3)

图片说的这一步太抽象了，不知道该怎么操作。

**Comment by 0000005** [comment]
https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4&viewFallbackFrom=powershell-7.1
官方说的这几个文件夹下都没有找到powershell的配置文件。

**Comment by aooohan** [comment]
> https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7.4&viewFallbackFrom=powershell-7.1 官方说的这几个文件夹下都没有找到powershell的配置文件。

默认是没有的,  手动创建一个就行
