### ISSUE TITLE
[Question] Powershell Hook语句似乎应该放$PROFILE文件入口处

### ISSUE THREAD

**Issue by LordHumphrey** [version-fox/vfox#99]
**Version**
The version you are currently using
VersionFox version 0.2.4
**OS**
macOS、Linux、Windows
Windows
**Question Description**
A clear and concise description of what the question is.
如果将`Invoke-Expression "$(vfox activate pwsh)"`放在`$PROFILE`最后，将会导致自定义的pwsh其他插件都失效
![image](https://github.com/version-fox/vfox/assets/43847411/152944e2-cb12-474c-bb1a-e90b8c46555c)

**Comment by aooohan** [comment]
应该是把你自定义的prompt函数覆盖了, 包装一下你初始的prompt函数应该就可以.
https://github.com/version-fox/vfox/blob/eef222df23cb53ed16865fceaa6bb544d0bf16ab/internal/shell/powershell.go#L36-L41

有兴趣提个pr修改一下吗 😄

**Comment by aooohan** [comment]
Fixed by #101
